### ISSUE TITLE
Batch variable highlighting is incorrect with escaped percent signs

### ISSUE THREAD

**Issue by riQQ** [ScintillaOrg/lexilla#11]
**Current situation**
```
{2}echo{0} {6}%%0{0}
{2}echo{0} %%%0
{2}echo{0} %%%%~-abcd
```
Notepad++ 7.9.5 Screenshot:
![Notepad++ screenshot](https://user-images.githubusercontent.com/3404787/119224478-df8dbe00-bafe-11eb-86c9-f89354e3df0f.png)

**Expected situation**
```
{2}echo{0} {6}%%0{0}
{2}echo{0} %%{6}%0{0}
{2}echo{0} %%{6}%%~-abcd{0}
```

**Comment by lifenjoiner** [comment]
> Expected situation
> {2}echo{0} {6}%%0{0}
> {2}echo{0} %%{6}%0{0}
> {2}echo{0} %%{6}%%~-abcd{0}

Is there anything wrong?
![test-escaped-percent](https://user-images.githubusercontent.com/19585474/119246320-3a80ed00-bbb3-11eb-9733-49ca75230b7c.png)

Maybe I'm wrong. To CMD, it seems to be:
```
{2}echo{0} %{6}%0{0}
{2}echo{6} %%%0{0}
{2}echo{6} %%%%{0}~-abcd{0}
```
or
```
{2}echo{0} %{6}%0{0}
{2}echo{0} %%{6}%0{0}
{2}echo{0} %%%%~-abcd{0}
```

**Comment by riQQ** [comment]
The problem is, that Lexilla doesn't look at the context. The echo statement could be part of a for loop body and then it could be a variable.

The really correct, but more complex solution would be to check if the current position is part of a for loop variable declaration or body and allow then mark `%%x` and `%%~<path-operators>x` as variables.

Without doing that, in my opinion the interpretation in my first post is second best solution and it's consistent.

**Comment by lifenjoiner** [comment]
One thing should be clear is that number could not be a variable of for loop.
With `for /?` you can find:
```
%variable  Specifies a single letter replaceable parameter.
```

**Comment by riQQ** [comment]
Have you tried it? It works for me and looks like the documentation is wrong.

**Comment by lifenjoiner** [comment]
Yeah, you're right, using a digital number as `for` loop variable works. But that makes me puzzled easily, as number is chosen to represent a callee argument. I would not write my scripts that way. I choose follow the standard manual.

I know it's tricky here, thinking the possibilities of both are uncertain. Actually:
1. Number as loop variable is special case.
2. It is a variable or argument is certain. May need more detection.

If it is not possible to distinguish them finally, that's it. Let's see if anyone has better suggestions.
Just some advice to make it better.

**Comment by nyamatongwe** [comment]
Committed with 7e2ef0e90a06529ef654d389ed6bc62c50eb6fc1 as it is an improvement.
