### ISSUE TITLE
F#: Signed integer literals are always lexed as decimal

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#110]
When lexing a signed integer literal, `SCE_FSHARP_NUMBER` is activated as soon as the operator is seen. Consequently the numeric base is never changed from the default of 10, as this logic is guarded by the `SCE_FSHARP_DEFAULT` case. Since binary and octal digits are just a subset of decimal, signed literals in these notations appear to be lexed properly, but the first hex digit > 9 prematurely terminates the number style:

![fsharp_signed_hex_literals](https://user-images.githubusercontent.com/59004801/197364224-b47597a3-d3ae-4cfa-aec3-8befe688f6e7.png)

Styling sign indicators like numbers is a design choice I'd prefer not to abandon [^1]. At the same time, an implementation that accidentally achieves its aim in 2/3 cases can probably be improved. This patch moves numeric base detection into the `SCE_FSHARP_NUMBER` case:

<del>[LexFSharp-Delay-base-detection-in-case-numeric-literals-are-signed.patch.txt](https://github.com/ScintillaOrg/lexilla/files/9845334/LexFSharp-Delay-base-detection-in-case-numeric-literals-are-signed.patch.txt)</del>

[^1]: A signed literal is a value; a unary operator plus a literal is an expression. Reducing syntax to a more atomic representation where feasible seems like a worthwhile goal for a lexer.

**Comment by rdipardo** [comment]
These are the tests: [Issue110-Tests.diff.txt](https://github.com/ScintillaOrg/lexilla/files/9845365/Issue110-Tests.diff.txt)

File names are not issue-specific since this patch is part of a planned series, and more test cases can simply be appended as was done with [FmtSpecs.fs](https://github.com/ScintillaOrg/lexilla/commits/master/test/examples/fsharp/FmtSpecs.fs).

**Comment by nyamatongwe** [comment]
This allows some new false successes since base characters will succeed after any 0, not just at start:
~~~f#
 let binB = -0b1010_0xf000
~~~

It may be OK to prioritize correct behaviour for `+0xA1B2C3D4` over diagnosing a problem with `-0b1010_0xf000`.

**Comment by rdipardo** [comment]
> This allows some new false successes since base characters will succeed after any 0

The problem is the `numericMetaChars1` character set. It gives the status of digits to all three notation prefixes ('b', 'o', 'x'). At one time that seemed like a convenient alternative to validating their position within the literal. The sequel to this patch was going to address it, but getting to it sooner is just as well.

This revision prunes the set of "combining or terminating" characters (`numericMetaChars1`). The radix of each literal is now checked only if the current value is the default, preventing a midway switch into a different base. Hexadecimals containing `0b` are still valid and not affected by the change:

[0002-Issue-110.revised.patch.txt](https://github.com/ScintillaOrg/lexilla/files/9846453/0002-Issue-110.revised.patch.txt)

Examples of invalid cases have been added to the tests:

[0002-Issue-110.expanded.tests.diff.txt](https://github.com/ScintillaOrg/lexilla/files/9846452/0002-Issue-110.expanded.tests.diff.txt)

**Comment by rdipardo** [comment]
Sorry, that last patch had a similar flaw to the first. Since the `currentBase == 10` condition is just a poor substitute for what the `SCE_FSHARP_DEFAULT` case label previously did, it will falsely match invalid decimal literals like `0123_0xcd`.

This next revision (somewhat verbosely) defines what can precede a numeric literal, namely whitespace or an operator [^1]:

[0003-Issue-110.further.revised.patch.txt](https://github.com/ScintillaOrg/lexilla/files/9847622/0003-Issue-110.further.revised.patch.txt)

Some new tests for invalid decimals were added: 

[0003-Issue-110.expanded.tests.for.decimals.diff.txt](https://github.com/ScintillaOrg/lexilla/files/9847621/0003-Issue-110.expanded.tests.for.decimals.diff.txt)

[^1]: The lexer has always switched to operator style [even without a space between operands][0].

[0]: https://github.com/ScintillaOrg/lexilla/blob/f5c2dfced19e4a3fcafeeb6749d25cc97758b4b9/lexers/LexFSharp.cxx#L594

**Comment by nyamatongwe** [comment]
Ouch! Just pushed.

**Comment by rdipardo** [comment]
It’s always possible when you’re in vastly different timezones.

There will be a follow-up patch in any case. It can be fixed then, or a
diff between versions 2 and 3 can be pushed in the meantime.
-- 
R. Di Pardo, Hon.B.A., M.A.

**Comment by nyamatongwe** [comment]
Included in 5.2.1 release.
