### ISSUE TITLE
Amend the previous patch to LexFSharp

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#111]
As belatedly observed in #110, the patch committed as bf913de lacked foresight regarding decimal literals that may improperly contain notation prefixes for other bases. This implements the needed correction, as explained [here]: 

[LexFSharp-amend-bf913de.patch.txt](https://github.com/ScintillaOrg/lexilla/files/9848661/LexFSharp-amend-bf913de.patch.txt)

[here]: https://github.com/ScintillaOrg/lexilla/issues/110#issuecomment-1288210024

**Comment by rdipardo** [comment]
This augments the committed test cases with some invalid decimal literals:

[Issue111-Tests.diff.txt](https://github.com/ScintillaOrg/lexilla/files/9848686/Issue111-Tests.diff.txt)

**Comment by nyamatongwe** [comment]
Included in 5.2.1 release.
