### ISSUE TITLE
F#: Add specifiers for 64-bit integer and floating point literals

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#112]
LexFSharp doesn't recognize 64-bit [integer literals] with the `L` or `UL` suffix, nor floating point literals in notations other than decimal, which end in `lf` or `LF` for single and double precision, respectively. Hexadecimal floats currently appear correct as `l` has always been a "combining or terminating" character (`numericMetaChars1`), and `f` matches a regular hex digit:

![fsharp_64b_literals](https://user-images.githubusercontent.com/59004801/198862248-2699c7bf-d10f-4eb3-b4c4-3910ecd21917.png)

This patch:

* adds the missing specifiers, including the capital `F` and `M` variants, for completeness
* reduces the `numericMetaChars1` character set to only the digit separator and both forms of the unsigned specifier: `u` and `U`
* shuffles the remaining specifiers into the "always terminating" character set (`numericMetaChars2`)

Because `e` and `E` are no longer classed as specifiers, the parsing rules for floats have been amended to prevent regressions. One collateral benefit is that arithmetic expressions with no intervening space will be operator-delimited, not fused into one literal as heretofore (*1).

[LexFSharp-Add-missing-specifiers-for-64-bit-numeric-literals.patch.txt](https://github.com/ScintillaOrg/lexilla/files/9895063/LexFSharp-Add-missing-specifiers-for-64-bit-numeric-literals.patch.txt)

_Follows #110_

---
(*1)

*Now*
![fsharp_arith_exprs](https://user-images.githubusercontent.com/59004801/198862659-2cb8dde7-4a92-472d-9c9e-de1af0bbb627.png)

*Patched*
![fsharp_arith_exprs_improved](https://user-images.githubusercontent.com/59004801/198862664-375bc63d-f73a-4efd-8cff-ee80af54ca67.png)

[integer literals]: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/literals#literal-types

**Comment by rdipardo** [comment]
These tests cover just the added features: [Issue112-Tests.diff.txt](https://github.com/ScintillaOrg/lexilla/files/9895097/Issue112-Tests.diff.txt)

**Comment by nyamatongwe** [comment]
Included in 5.2.1 release.
