### ISSUE TITLE
Batch: Remark and comment styles in strings

### ISSUE THREAD

**Issue by mpheath** [ScintillaOrg/lexilla#115]
Remarks and comments can be comment style in strings and continue to the end of the line.

This is before and after patching:

![Issue115](https://user-images.githubusercontent.com/58158242/200114985-fa2029bf-567a-44c8-9f95-0051013a782b.gif)

I did the fix even though tested the same document with Notepad 2 which colours strings... with it's batch lexer and does not have this issue. So, the patch is just a fix, not an upgrade to be as good as the Notepad 2 batch lexer. :(

I updated the patched code that was commited previously and replaced `strlen(wordBuffer)` with `wbl` as the later already stores the value of `strlen(wordBuffer)`. 

I changed `textQuoted()` to also handle single quoted strings which are used to enclose `for` loop command strings. I am not aware of any side effects of this. Perhaps a command like `powershell 'arg1' 'arg2'` which can have single quotes though doubt would be an issue.

Full LexBatch.cxx file and test files:

[batch.zip](https://github.com/ScintillaOrg/lexilla/files/9943542/batch.zip)

**Comment by nyamatongwe** [comment]
Committed with some code changes.

There was an explicit NUL `\0` in the `strQuotes` variable that didn't have any effect and looked weird so was removed. For harmonious types, `strlen` returns `size_t` so derived variables `strLength` and `i` were changed to `size_t`. Added `const` and moved declarations where recommended by linters.

**Comment by nyamatongwe** [comment]
Included in 5.2.1 release.
