### ISSUE TITLE
Are different background colors available for alternate lines?

### ISSUE THREAD

**Issue by paul1149** [ScintillaOrg/lexilla#119]
Hi. If this is the wrong place for this question, please delete and/or direct me elsewhere.

I use geany on Linux, and mostly for text work, not programming. The window is generally a fairly solid block of text, and it would be helpful for the eyes for alternate lines to have slightly different background colors, as is normal in many spreadsheets with tight displays.

Is that possible? Thanks.

**Comment by nyamatongwe** [comment]
This is an issue for the edit component Scintilla, not Lexilla which is about understanding particular languages. The [feature request tracker for Scintilla](https://sourceforge.net/p/scintilla/feature-requests/) is on SourceForge.

**Comment by paul1149** [comment]
Ok, thanks very much.
