### ISSUE TITLE
Using non-ASCII symbols

### ISSUE THREAD

**Issue by PaulStogov** [ScintillaOrg/lexilla#130]
Hello! I'm a big fan of Geany IDE which use lexilla. I tried to add a coloring scheme for the internal basic-like language of 1C software which use cyrillic symbols in names of operators. Found out that the coloring doesn't work if keywords start with any non-ASCII symbol. It there a way to override this behavior? Thanks in advance.

**Comment by nyamatongwe** [comment]
Which lexer are you using?

**Comment by PaulStogov** [comment]
lexer_filetype=C

**Comment by nyamatongwe** [comment]
Please add an example file that illustrates the problem.

**Comment by PaulStogov** [comment]
I've sent them by email. Any conclusions? 
P.S. It's mostly a reminder for me myself, sorry.

**Comment by nyamatongwe** [comment]
I haven't found any email.

Files, with a .txt extension, can be attached to this issue by dragging them into a reply edit box.

**Comment by PaulStogov** [comment]
![image](https://user-images.githubusercontent.com/1442851/216714758-056e1e1d-ecb8-46e7-8451-3cbab6be7301.png)
[filetypes.1C.conf.txt](https://github.com/ScintillaOrg/lexilla/files/10582932/filetypes.1C.conf.txt)
[filetype_extensions.conf.txt](https://github.com/ScintillaOrg/lexilla/files/10582933/filetype_extensions.conf.txt)
[example.1c.txt](https://github.com/ScintillaOrg/lexilla/files/10582934/example.1c.txt)

**Comment by nyamatongwe** [comment]
Fix committed with c1a8d798e2cad76aae9d4425819be0800bb8a3ef. The bug was introduced with 9fe21acd7107a2e735fcdd1fafa6fec31d90a748 in 2018.

**Comment by PaulStogov** [comment]
Thank you!

**Comment by nyamatongwe** [comment]
Fixed in 5.2.2.
