### ISSUE TITLE
[Ruby] Fix range literal highlighting

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#139]
This is for https://sourceforge.net/p/scintilla/bugs/1018/

https://docs.ruby-lang.org/en/master/syntax/literals_rdoc.html#label-Range+Literals
```ruby
(1..2)  # includes its ending value
(1...2) # excludes its ending value
(1..)   # endless range, representing infinite sequence from 1 to Infinity
(..1)   # beginless range, representing infinite sequence from -Infinity to 1
```

**Comment by nyamatongwe** [comment]
Is this proposing a range literal class? These aren't numbers so shouldn't be `SCE_RB_NUMBER`.

**Comment by zufuliu** [comment]
No, just highlight dot as operator instead of part of number.

**Comment by nyamatongwe** [comment]
Dots are currently highlighted as `SCE_RB_OPERATOR` in these cases.

**Comment by zufuliu** [comment]
OK.
