### ISSUE TITLE
Do not enable CETCOMPAT for ARM64 builds

### ISSUE THREAD

**Issue by matbech** [ScintillaOrg/lexilla#14]
In commit: https://github.com/ScintillaOrg/lexilla/commit/7728600a9f01a3b9ebbfe9f6cec6679dc7fb7b5e
CETCOMPAT is enabled for all build configurations. However, if this is enabled for ARM64, the following link error is emitted:
1>LINK : fatal error LNK1246: '/CETCOMPAT' not compatible with 'ARM64' target machine; link without '/CETCOMPAT'

The solution is to enable CETCOMPAT only for x64 and Win32 build configurations.

**Comment by nyamatongwe** [comment]
Fixed with b496cbb.
