### ISSUE TITLE
[Ruby] Highlight `#@`, `#@@` and `#$` style interpolation

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#140]
This is for https://sourceforge.net/p/scintilla/bugs/1018/

https://docs.ruby-lang.org/en/master/syntax/literals_rdoc.html#label-String+Literals
> You can also use #@foo, #@@foo and #$foo as a shorthand for, respectively, #{ @foo }, #{ @@foo } and #{ $foo }

**Comment by zufuliu** [comment]
[ruby-0218.zip](https://github.com/ScintillaOrg/lexilla/files/10773666/ruby-0218.zip)

Patch highlight `#` as SCE_RB_OPERATOR (similar to `#{}`) and reset as variables.

**Comment by nyamatongwe** [comment]
The change produces `Expression: pos >= startSeg` assertions in `ColourTo` from line 1145 inside `ColouriseRbDoc` for this example:
~~~ruby
"#{1}"
~~~

**Comment by zufuliu** [comment]
[ruby-0219.zip](https://github.com/ScintillaOrg/lexilla/files/10775354/ruby-0219.zip)

Fixed, due to lost `advance_char(i, ch, chNext, chNext2);`.

**Comment by nyamatongwe** [comment]
Included in 5.2.3.
