### ISSUE TITLE
Switch fallthrough attribute

### ISSUE THREAD

**Issue by ozone10** [ScintillaOrg/lexilla#143]
I am testing [C5262](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5262?view=msvc-170) warning/error for Notepad++.

And sometimes I use command line to enable code analysis with that warning, which also enable it for both Lexilla and Scintilla projects.
Because I also sometimes build with warnings as error, the build will fail because Lexilla has few C5262 warnings. 

@nyamatongwe 
And since Lexilla use c++17, could it use `[[fallthrough]]` attribute, instead of comments?

**Comment by nyamatongwe** [comment]
Closing as rejected,
