### ISSUE TITLE
GDScript Lexer does not support `$` and `%` symbols

### ISSUE THREAD

**Issue by 3fTL** [ScintillaOrg/lexilla#145]
In GDScript `$` and `%` should be highlighted separately, with something like SCE_GD_GETNODE. 

`$` https://docs.godotengine.org/en/stable/tutorials/scripting/nodes_and_scene_instances.html#syntactic-sugar
https://docs.godotengine.org/en/stable/tutorials/best_practices/scene_organization.html#how-to-build-relationships-effectively
https://docs.godotengine.org/en/stable/tutorials/best_practices/godot_interfaces.html#acquiring-object-references

`%` Unique nodes: https://docs.godotengine.org/en/stable/tutorials/scripting/scene_unique_nodes.html

![Untitled](https://user-images.githubusercontent.com/114991498/223462312-ef8764c0-e962-4e64-8a8c-30869f60b488.png)
![image](https://user-images.githubusercontent.com/114991498/223530602-779dbf85-1dad-40fd-9dfa-124f7c02bfda.png)

**Comment by nyamatongwe** [comment]
This report should include links to documentation on the features being recognised. That helps maintainers to understand future issues involving the new lexical class.

**Comment by nyamatongwe** [comment]
Included in version 5.2.4.
