### ISSUE TITLE
Python PEP 701 f-strings changes

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#150]
https://peps.python.org/pep-0701/
https://discuss.python.org/t/pep-701-syntactic-formalization-of-f-strings/22046

```python
# https://peps.python.org/pep-0701/#rationale
f"{f"{f"infinite"}"}" + " " + f"{f"nesting!!!"}"
f"{'\n'.join(a)}"

# https://discuss.python.org/t/pep-701-syntactic-formalization-of-f-strings/22046/93
f"___{
    x
}___"
```

**Comment by zufuliu** [comment]
It's available in Python 3.12 beta1 https://www.python.org/downloads/release/python-3120b1/

Also  per https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals
> New in version 3.8: The equal sign '='.

**Comment by zufuliu** [comment]
I'm not familiar with LexPython.cxx, it seems the restriction on f-string can be removed (for the sake of PEP 701 or Python 3.12+) by delete following block at begging of `LexerPython::ProcessLineEnd()`:
https://github.com/ScintillaOrg/lexilla/blob/e04dd0ff7ce2c9d147e023c4e4452d1b108ec495/lexers/LexPython.cxx#L495-L511

**Comment by nyamatongwe** [comment]
@jpe, could you please look at the above change?

**Comment by jpe** [comment]
I have changes that I worked on separately, though I was going to use them for a bit to see if there were any problems. I'll submit them as a pull request.

**Comment by nyamatongwe** [comment]
> I'll submit them as a pull request.

#209

**Comment by zufuliu** [comment]
Python 3.12 (with Unicode 15.0) is released.
https://www.python.org/downloads/release/python-3120/
