### ISSUE TITLE
[VB.NET] Support for multiline strings

### ISSUE THREAD

**Issue by xv** [ScintillaOrg/lexilla#151]
Hi! Support for multiline strings was added in [VB.NET 14](https://learn.microsoft.com/en-us/archive/msdn-magazine/2015/january/visual-basic-net-14-top-improvements-in-visual-basic-14) (released in 2015).

I came across broken highlighting for one of my code files and saw that [LexVB.cxx](https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexVB.cxx) does not support multiline strings. So, naturally I forked and patched.

I have gated the support for the feature behind the property `lexer.vb.strings.multiline` for the sake of downstream compatibility, though I am not sure if something else is preferred.

Preview of the change:
<img src="https://i.imgur.com/vX7SpAF.png" height="250">

Attached is a patch file containing the changes, including a test case for the feature.
[vbnet14_multiline_str.patch](https://github.com/ScintillaOrg/lexilla/files/10999383/vbnet14_multiline_str.patch)

Thank you.

**Comment by nyamatongwe** [comment]
Committed. Added a marker comment so that applications like SciTE can document the property.

**Comment by nyamatongwe** [comment]
Included in release 5.2.5.
