### ISSUE TITLE
Compiling with "make CLANG=1 GTK3=1" under ubuntu 22.04 will cause Ctrl+F2 to not work

### ISSUE THREAD

**Issue by egsoho** [ScintillaOrg/lexilla#152]
I downloaded the latest scite535.tgz and compiled it with "make CLANG=1 GTK3=1" under ubuntu 22.04,
Under the compiled SciTE, I cannot use Ctrl+F2 to Toggle Bookmark, I can only switch by clicking Toggle Bookmark under the menu, and Ctrl+F6 and Ctrl+F11 also have this problem.
I use "make CLANG=1 GTK3=1" to compile under ubuntu 20.04, and there is no such problem under the compiled SciTE.
I later found out that it was caused by GTK3=1, after canceling GTK3=1 and recompiling, there is no such problem

**Comment by nyamatongwe** [comment]
This issue tracker is for the Lexilla library which performs lexing of programming languages and is used by SciTE. SciTE and Scintilla are housed on SourceForge and bugs should be reported on the Scintilla bug tracker there: https://sourceforge.net/p/scintilla/bugs/.

I couldn't work out what was really happening here: GTK may be ignoring the `GDK_CONTROL_MASK` flag when searching for the command matching the key press. If the `F2` binding is removed, `Ctrl+F2` works. The problem occurs for other similar cases like `Ctrl+F11` which should be Use Monospaced Font but instead performs Full Screen assigned to `F11`. To work around the problem, explicit checking for the control F-Key bindings was added in the lower level key press handler.
https://sourceforge.net/p/scintilla/scite/ci/49041f379f4f06bc88c8d4b0fd5b9bdb3c0eeeb2/
