### ISSUE TITLE
Use Heterogeneous Lookup

### ISSUE THREAD

**Issue by matbech** [ScintillaOrg/lexilla#16]
You may want to use Heterogeneous Lookup in here:
https://github.com/ScintillaOrg/lexilla/blob/master/lexlib/PropSetSimple.cxx#L52
More details:
https://abseil.io/tips/144

Change
typedef std::map<std::string, std::string> mapss;
to
typedef std::map<std::string, std::string, std::less<>> mapss;

and then change:
mapss::const_iterator keyPos = props->find(std::string(key));
to
mapss::const_iterator keyPos = props->find(key);

On another note, I'm surprised why you don't make your life easier using the auto keyword among many other language improvements.

**Comment by nyamatongwe** [comment]
Is this in response to the use of heterogeneous lookup in https://sourceforge.net/p/scintilla/feature-requests/1129/#a454/08ea ?

Currently I'm an 'almost-never-auto' as it obscures the types being manipulated. `auto` isn't that much shorter than `mapss::iterator`. To me, `auto` is only really worthwhile when the type is more complex.

**Comment by matbech** [comment]
> Is this in response to the use of heterogeneous lookup in https://sourceforge.net/p/scintilla/feature-requests/1129/#a454/08ea ?
Oh I haven't followed the discussion on sourceforge. I was just reviewing your latest git commit.

**Comment by nyamatongwe** [comment]
Committed change aaefcf15828605e219bb411e8dc8a78cfa65e35b which includes heterogeneous lookup.

Changes 35a6b946b17441712034031eba9880cf458b7827 and 44f6ac8a323f6b09e2163ccaa72de1f86e467e8c also use heterogeneous lookup.
