### ISSUE TITLE
Possible SCI_DESCRIBEKEYWORDSETS issue

### ISSUE THREAD

**Issue by dail8859** [ScintillaOrg/lexilla#175]
Scintilla 5.3.5
Lexilla 5.2.5
Windows 11
Qt 6.5.1

---

I'm setting the Scintilla editor's lexer to `"phpscript"` and getting it to style the document correctly.

However when I call `editor->describeKeyWordSets()` it is not returning the result I'd expect.

Lexer `"phpscript"` uses one keyword list (index 4):

https://github.com/ScintillaOrg/lexilla/blob/a6b8fca07b62e603fb446849f4df24f01c11f15c/lexers/LexHTML.cxx#L722-L730

So I had expected `editor->describeKeyWordSets()` to return the string `"\n\n\n\nPHP keywords\n"`. Since index 4 is the only valid keyword set that PHP uses.

However `editor->describeKeyWordSets()` is returning `"PHP keywords\n"` which would seem to incorrectly indicate that the lexer supports two lists, index 0 being `"PHP keywords"` and index 1 being `""`

Thoughts?

**Comment by nyamatongwe** [comment]
`DefineWordListSets` isn't expecting empty entries: 
~~~c++
	void DefineWordListSets(const char * const wordListDescriptions[]) {
		if (wordListDescriptions) {
			for (size_t wl = 0; wordListDescriptions[wl]; wl++) {
				if (!wordLists.empty())
					wordLists += "\n";
				wordLists += wordListDescriptions[wl];
~~~

I expect the `!wordLists.empty()` conddition should be replaced with `wl > 0`.
