### ISSUE TITLE
BASH HEREDOC color for ending DELIMITER

### ISSUE THREAD

**Issue by RobMahn** [ScintillaOrg/lexilla#177]
**Description of the Issue**
In a BASH script, the HEREDOC ending delimiter is colored in the style of HERE Q
instead of HERE DELIM.

Thus, the delimiter colors do not match and then ending delimiter looks like HEREDOC content.

**Steps to Reproduce the Issue**
A similar report was not found in the issue tracker.
Uninstall Notepad++ and rename %APPDATA%/Notepad++
Install Notepad++ v8.5.3 (64-bit) on Windows 11 Pro version 10.0.22621 Build 22621
Hence, plugins were not installed.
Create a document with a .sh extension
Enter the following:
```
cat <<HERE_DOC_DELIMITER

Here document content, colored as default style HERE Q

HERE_DOC_DELIMITER
```

**Expected Behavior**
Both the beginning and ending HEREDOC delimiters would be colored as defined in the default style as HERE DELIM.

**Actual Behavior**
Then ending HEREDOC delimiter was colored as defined in the default style as HERE Q.

![image](https://github.com/ScintillaOrg/lexilla/assets/35499889/923dcd03-114c-40c8-823c-7a0621c57aa1)

**Debug Information**
Notepad++ v8.5.3 (64-bit)
Build time : May 15 2023 - 06:09:36
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1702

**Comment by zufuliu** [comment]
It's seems intended (to make code folding works?), especially when the delimiter is empty.
```bash
cat <<''
line 1
line 2

echo line after heredoc
```

**Comment by zufuliu** [comment]
First patch to fix (`styler.StyleAt(i+1) == SCE_SH_DEFAULT`) and simplify heredoc folding.

[bash-heredoc-fold.patch](https://github.com/ScintillaOrg/lexilla/files/11716006/bash-heredoc-fold.patch)

**Comment by zufuliu** [comment]
Highlight end delimiter.
[bash-heredoc-end-delimiter.patch](https://github.com/ScintillaOrg/lexilla/files/11744518/bash-heredoc-end-delimiter.patch)
