### ISSUE TITLE
bash syntax highlighting broken with $ sign inside double quotes

### ISSUE THREAD

**Issue by ifschulz** [ScintillaOrg/lexilla#180]
There seems to be an issue with bash syntax highlighting when using a ‘$’ as the last character of a double quoted string. Up to notepad++-v8.5.3 everything was fine, but with v8.5.4 it breaks the syntax highlighting to the end of the document:

v8.5.3:

![2023-07-10 23_11_59-_new 1 - Notepad++](https://github.com/ScintillaOrg/lexilla/assets/139175247/290a9c2a-0d13-497e-9b2b-04447f6e6458)

v8.5.4:

![2023-07-10 23_25_04-_new 4 - Notepad++](https://github.com/ScintillaOrg/lexilla/assets/139175247/a9b24500-226b-4560-b842-5dac4c00a7ae)

This can of course be fixed with escaping the ‘$’ sign:

![2023-07-10 23_25_42-_new 4 - Notepad++](https://github.com/ScintillaOrg/lexilla/assets/139175247/4e60e60b-337d-407a-b219-3832d0977853)

Even though using an unescaped ‘$’ sign inside double quotes (when not referencing a variable) is not best practice, it should still not break the syntax highlighting.

**Comment by zufuliu** [comment]
It's due following code, which should be disabled for `String`, `LString`, and `HereDoc`:
https://github.com/ScintillaOrg/lexilla/blob/f157108fe3afba3bead2aab44f5ede25cbecece7/lexers/LexBash.cxx#L331-L336

it can be fixed by passing a parameter to `Expand()` or added a method to `QuoteStackCls`, not sure what would be a good name.

**Comment by zufuliu** [comment]
A simple fix:
```diff
diff --git a/lexers/LexBash.cxx b/lexers/LexBash.cxx
index 4945ef70..bc7cff71 100644
--- a/lexers/LexBash.cxx
+++ b/lexers/LexBash.cxx
@@ -864,7 +864,7 @@ void SCI_METHOD LexerBash::Lex(Sci_PositionU startPos, Sci_Position length, int
 							if (stylingInside) {
 								sc.SetState(SCE_SH_BACKTICKS | insideCommand);
 							}
-						} else if (sc.ch == '$') {
+						} else if (sc.ch == '$' && !AnyOf(sc.chNext, '\"', '\'')) {
 							QuoteStack.Expand(sc, cmdState, stylingInside);
 							continue;
 						}
```

**Comment by nyamatongwe** [comment]
Example as text:
~~~bash
egrep '^[A-Z]$'
test=foobar

egrep "^[A-Z]$"
test=foobar

egrep "^[A-Z]\$"
test=foobar
~~~

Check in Linux for:
~~~bash
echo '$'
echo "$"
echo "$"
echo "$"x""
~~~
Result:
~~~bash
>bash 180example.sh
$
$
$
$x
>Exit code: 0
~~~

**Comment by zufuliu** [comment]
C-String test case:
```bash
echo x$'\t'y
echo "x$'\t'y"
echo "x\ty"
```

**Comment by zufuliu** [comment]
It seems to fully fix this we need a list of all special variables (the `&& !AnyOf(sc.chNext, '\"', '\'')`  part is still needed for string/heredoc block), current code teat all punctuation and white spaces as single character special variable. there is another bug reported at https://github.com/zufuliu/notepad2/issues/684: 
![image](https://user-images.githubusercontent.com/38994291/253325478-522c9abf-6432-4dae-bf03-8788fe23edb6.png)

Bash special variables are list at https://www.gnu.org/software/bash/manual/bash.html#Variable-Index

**Comment by zufuliu** [comment]
> It seems to fully fix this we need a list of all special variables (the `&& !AnyOf(sc.chNext, '\"', '\'')` part is still needed for string/heredoc block), current code teat all punctuation and white spaces as single character special variable. there is another bug reported at [zufuliu/notepad2#684](https://github.com/zufuliu/notepad2/issues/684): ![image](https://user-images.githubusercontent.com/38994291/253325478-522c9abf-6432-4dae-bf03-8788fe23edb6.png)

Created #184 as separate issue.
