### ISSUE TITLE
[Bash] restore cmdState after shell expansion

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#182]
As reported at https://github.com/zufuliu/notepad2/issues/684:
![image](https://user-images.githubusercontent.com/38994291/253322659-62358a5e-1eef-4948-bb28-12adfc813c96.png)
`cmdState` is reset to `CmdState::Body` after shell expansions, which causes failure for keyword highlighting at
https://github.com/ScintillaOrg/lexilla/blob/f157108fe3afba3bead2aab44f5ede25cbecece7/lexers/LexBash.cxx#L656-L660

the bug report for bracket test can be fixed by checking `testExprType`, a better fix seems to be store `cmdState` in `QuoteCls` (similar to `Outer`).

**Comment by nyamatongwe** [comment]
This styles the `then` as 8 `SCE_SH_IDENTIFIER` instead of 4 `SCE_SH_WORD`. Before patch, `then` was `SCE_SH_WORD`.

~~~bash
if [ -n "$eth" -o -n "$wlan"]; then
fi
~~~
![Bash182](https://github.com/ScintillaOrg/lexilla/assets/225818/aaeeb6ba-5511-4a64-bbf4-d222bc2ca9f3)

**Comment by zufuliu** [comment]
It's bug in the test, space before `]` is required for bracket test:
https://github.com/ScintillaOrg/lexilla/blob/f157108fe3afba3bead2aab44f5ede25cbecece7/lexers/LexBash.cxx#L1085-L1092

Before the patch, `cmdState` is set to `CmdState::Body` after close double quote character.
