### ISSUE TITLE
Line comments in ASP scripts do not terminate

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#185]
- *Cross-post of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13901*

---

When the value of `asp.default.language` is 2 ("assume scripts are ASP"),[^1] line comments are not terminated inside [legacy-style][1] code blocks (`<%...%>`), e.g.

##### Text

~~~asp
<html>
  <% 'comment %>
</html>
~~~

##### Styles

~~~
{1}<html>{0}
  {15}<%{81} {82}'comment %>{81}
</{86}html{81}>
~~~

The same occurs within ASP [string-interpolation][2] tags, [data-binding][3] tags, and so-called [expression builders][4].
The exceptions are [directive expressions][5] and [server-side comments][6], apparently because they activate states which don't permit nested styles; `SCE_H_ASPAT` (16) in the former's case:

~~~
{1}<html>{0}
  {15}<%@{16} 'comment {15}%>{0}
{1}</html>{0}
~~~

`SCE_H_XCCOMMENT` (20) in the latter:

~~~
{1}<html>{0}
  {15}<%--{20} 'comment --{15}%>{0}
{1}</html>{0}
~~~

[^1]: Given the default option value ("assume scripts are JS"), line comments are (correctly) taken for single-quoted JavaScript strings.

[1]:  https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/inline-expressions#---embedded-code-blocks
[2]: https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/inline-expressions#---displaying-expression
[3]: https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/inline-expressions#---data-binding-expression
[4]: https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/inline-expressions#---expression-builder
[5]: https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/inline-expressions#---directive-expression
[6]: https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/inline-expressions#--------server-side-comments-block

**Comment by nyamatongwe** [comment]
There have been issues around script termination inside comments and string literals before like [Scintilla Bug #650](https://sourceforge.net/p/scintilla/bugs/650/). Some of these have been decided the opposite way because some states suppress script termination until they are terminated.

What is the actual behaviour of ASP in this case?

**Comment by zufuliu** [comment]
How about extend `stateAllowsTermination()` to also check `ch` and `chNext`? the failure example at https://sourceforge.net/p/scintilla/bugs/650/#82e0/fefe ternimated at `?>`, but it's not ASP.

**Comment by zufuliu** [comment]
A simple fix:
```diff
@@ -216,11 +216,13 @@ inline bool isStringState(int state) {
 	return bResult;
 }
 
-inline bool stateAllowsTermination(int state) {
+inline bool stateAllowsTermination(int state, int ch) {
 	bool allowTermination = !isStringState(state);
 	if (allowTermination) {
 		switch (state) {
 		case SCE_HB_COMMENTLINE:
+			allowTermination = ch == '%'; // %>
+			break;
 		case SCE_HPHP_COMMENT:
 		case SCE_HP_COMMENTLINE:
 		case SCE_HPA_COMMENTLINE
```

[asp-comment-0716.zip](https://github.com/ScintillaOrg/lexilla/files/12063031/asp-comment-0716.zip)

![image](https://github.com/ScintillaOrg/lexilla/assets/2289926/d37aa7c2-2b70-4924-a69d-f5d9b3c493cd)

**Comment by rdipardo** [comment]
This one-liner also appears to work, though it's possible I've underestimated the problem: 

~~~diff
diff --git a/lexers/LexHTML.cxx b/lexers/LexHTML.cxx
index 48e4b919..846f0042 100644
--- a/lexers/LexHTML.cxx
+++ b/lexers/LexHTML.cxx
@@ -2258,7 +2258,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 			}
 			break;
 		case SCE_HB_COMMENTLINE:
-			if (ch == '\r' || ch == '\n') {
+			if (ch == '\r' || ch == '\n' || isMakoBlockEnd(chNext, chNext2, makoBlockType)) {
 				styler.ColourTo(i - 1, StateToPrint);
 				state = SCE_HB_DEFAULT;
 			}
~~~

[0001-185-Terminate-ASP-comments-when-the-end-tag-is-seen.patch.txt](https://github.com/ScintillaOrg/lexilla/files/12065594/0001-185-Terminate-ASP-comments-when-the-end-tag-is-seen.patch.txt)

**Comment by rdipardo** [comment]
> What is the actual behaviour of ASP in this case?

The original bug reports would suggest that VB comments are supposed to terminate before the closing tag.

> the failure example at https://sourceforge.net/p/scintilla/bugs/650/#82e0/fefe ternimated at `?>`, but it's not ASP.

Remember I said that `asp.default.language` has to be `2`. Applications like Notepad++ [prepare the buffer][0] in this way to simulate an ASP "file type".


[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9122dc64fab477fd451f7ac92107f326a9f4d5e2/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L749-L761

**Comment by rdipardo** [comment]
This iteration doesn't require a whitespace before the closing tag:

~~~diff
diff --git a/lexers/LexHTML.cxx b/lexers/LexHTML.cxx
index 48e4b919..a643d605 100644
--- a/lexers/LexHTML.cxx
+++ b/lexers/LexHTML.cxx
@@ -2261,6 +2261,9 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 			if (ch == '\r' || ch == '\n') {
 				styler.ColourTo(i - 1, StateToPrint);
 				state = SCE_HB_DEFAULT;
+			} else if (isMakoBlockEnd(chNext, chNext2, makoBlockType)) {
+				styler.ColourTo(i, StateToPrint);
+				state = SCE_HB_DEFAULT;
 			}
 			break;
 		case SCE_HB_STRINGEOL:
~~~

[0002-185-Terminate-ASP-comments-when-the-end-tag-is-seen.patch.txt](https://github.com/ScintillaOrg/lexilla/files/12065901/0002-185-Terminate-ASP-comments-when-the-end-tag-is-seen.patch.txt)

**Comment by zufuliu** [comment]
> but it's not ASP.

What I want to say is `?>` is not ASP close tag, so should not terminate line comment at `'UTF-8'?>`.

I think Mako is for a different thing than ASP? see #187 for related issue where I think it's better to change `stateAllowsTermination()` to check the end tag.

**Comment by nyamatongwe** [comment]
Mako is [Mako Templates for Python](https://www.makotemplates.org/).

**Comment by nyamatongwe** [comment]
After installing IIS this example can be run:
~~~asp
<!DOCTYPE html>
<html>
Start
<%response.write("1")%>
<% x="2"'comment %>
<%response.write(x)%>
End
</html>
~~~

Which looks like.
![ASPBasicComment](https://github.com/ScintillaOrg/lexilla/assets/225818/d093a011-6038-44ac-bab3-ec488855686d)

**Comment by zufuliu** [comment]
> ```c++
> } else if ((chNext == '%') && (chNext2 == '>')) {
> ```

This will break client VBScript comment line, which terminated at eol or `</script>` (can be handled same as `SCE_HJ_COMMENTLINE`). also server side JavaScript comment line has same bug (terminated at `?>` instead of `%>`).

Update patch for both bug:
```diff
diff --git a/lexers/LexHTML.cxx b/lexers/LexHTML.cxx
index 48e4b919..672a4e3b 100644
--- a/lexers/LexHTML.cxx
+++ b/lexers/LexHTML.cxx
@@ -216,11 +216,14 @@ inline bool isStringState(int state) {
 	return bResult;
 }
 
-inline bool stateAllowsTermination(int state) {
+inline bool stateAllowsTermination(int state, int ch) {
 	bool allowTermination = !isStringState(state);
 	if (allowTermination) {
 		switch (state) {
 		case SCE_HB_COMMENTLINE:
+		case SCE_HJ_COMMENTLINE:
+			allowTermination = ch == '%'; // %>
+			break;
 		case SCE_HPHP_COMMENT:
 		case SCE_HP_COMMENTLINE:
 		case SCE_HPA_COMMENTLINE:
@@ -230,6 +233,10 @@ inline bool stateAllowsTermination(int state) {
 	return allowTermination;
 }
 
+inline bool stateAllowsTermination(int state) {
+	return stateAllowsTermination(state, 0);
+}
+
 // not really well done, since it's only comments that should lex the %> and <%
 inline bool isCommentASPState(int state) {
 	bool bResult;
@@ -1327,7 +1334,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 			case SCE_HJ_COMMENTDOC:
 			//case SCE_HJ_COMMENTLINE: // removed as this is a common thing done to hide
 			// the end of script marker from some JS interpreters.
-			case SCE_HB_COMMENTLINE:
+			//case SCE_HB_COMMENTLINE:
 			case SCE_HBA_COMMENTLINE:
 			case SCE_HJ_DOUBLESTRING:
 			case SCE_HJ_SINGLESTRING:
@@ -1345,7 +1352,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 			default :
 				// check if the closing tag is a script tag
 				if (const char *tag =
-						state == SCE_HJ_COMMENTLINE || isXml ? "script" :
+						(state == SCE_HJ_COMMENTLINE || state == SCE_HB_COMMENTLINE || isXml) ? "script" :
 						state == SCE_H_COMMENT ? "comment" : 0) {
 					Sci_Position j = i + 2;
 					int chr;
@@ -1634,7 +1641,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 
 		// handle the end of a pre-processor = Non-HTML
 		else if ((!isMako && !isDjango && ((inScriptType == eNonHtmlPreProc) || (inScriptType == eNonHtmlScriptPreProc)) &&
-				  (((scriptLanguage != eScriptNone) && stateAllowsTermination(state))) &&
+				  (((scriptLanguage != eScriptNone) && stateAllowsTermination(state, ch))) &&
 				  (((ch == '%') || (ch == '?')) && (chNext == '>'))) ||
 		         ((scriptLanguage == eScriptSGML) && (ch == '>') && (state != SCE_H_SGML_COMMENT))) {
 			if (state == SCE_H_ASPAT) {
```

[asp-comment-0719.patch](https://github.com/ScintillaOrg/lexilla/files/12093956/asp-comment-0719.patch)

**Comment by nyamatongwe** [comment]
> @zufuliu This will break client VBScript comment line

I don't see a problem with client VBScript comment lines with the change. If there was a problem then `StateToPrint` can be checked.
~~~asp
<!DOCTYPE html>
<html>
<script type="text/vbscript">
'%>
'?>
</script>
<script type="text/vbscript">
var e="%>"
var f="?>"
</script>
Start
<%response.write("1")%>
<% x="2"'comment %>
<%response.write(x)%>
End
</html>
~~~

>  server side JavaScript comment line has same bug (terminated at ?>
~~~asp
<%@language=javascript%>
<%x=3;//comment%>
<%x=3;//comment ?> %>
~~~

There may be other serer-side possibilities for `<?` .. `?>` but if the lexer only wants PHP here then `?>` could be accepted only in a PHP mode.

**Comment by nyamatongwe** [comment]
It may be clearer to separate out the PHP and ASP (and similar) pre-processor cases at
~~~c++
// handle the end of a pre-processor = Non-HTML
~~~

**Comment by zufuliu** [comment]
> I don't see a problem with client VBScript comment lines with the change.

it will has problem for following code:
```html
<script type="text/vbscript">
'1%>2
'1?>2
</script>
```

**Comment by zufuliu** [comment]
> separate out the PHP and ASP (and similar) pre-processor cases

What about replace `((ch == '%') || (ch == '?'))` with a helper function, e.g.:
```c++
inline bool isPreProcessorEndTag(int state, int ch) {
	const script_mode mode = ScriptOfState(state);
	if (state == SCE_H_ASP || state == SCE_H_ASPAT || mode == eScriptVBS || mode == eScriptJS || mode == eScriptPython) {
		return ch == '%';
	}
	if (mode == eScriptPHP) {
		return ch == '%' || ch == '?';
	}
	return ch == '?';
}
```

**Comment by nyamatongwe** [comment]
> @zufuliu it will has problem for following code:

Changing the condition to check `StateToPrint` helps that case.
~~~c++
} else if ((StateToPrint == SCE_HBA_COMMENTLINE) && ((chNext == '%') && (chNext2 == '>'))) {
	styler.ColourTo(i, StateToPrint);
	state = SCE_HB_DEFAULT;
~~~
<img width="281" alt="ASPServerBasic" src="https://github.com/ScintillaOrg/lexilla/assets/225818/19019fa1-841c-43d3-b69c-0f9536cf04d4">

**Comment by nyamatongwe** [comment]
> @zufuliu replace ((ch == '%') || (ch == '?')) with a helper function

Something like that seems sensible. The `ScriptOfState` needs type agreement: possibly `script_type` instead of `script_mode`.

**Comment by zufuliu** [comment]
OK, then following is the patch:
[asp-comment-0720.patch](https://github.com/ScintillaOrg/lexilla/files/12105532/asp-comment-0720.patch)
```diff
diff --git a/lexers/LexHTML.cxx b/lexers/LexHTML.cxx
index 48e4b919..7615feb1 100644
--- a/lexers/LexHTML.cxx
+++ b/lexers/LexHTML.cxx
@@ -220,7 +220,6 @@ inline bool stateAllowsTermination(int state) {
 	bool allowTermination = !isStringState(state);
 	if (allowTermination) {
 		switch (state) {
-		case SCE_HB_COMMENTLINE:
 		case SCE_HPHP_COMMENT:
 		case SCE_HP_COMMENTLINE:
 		case SCE_HPA_COMMENTLINE:
@@ -230,6 +229,17 @@ inline bool stateAllowsTermination(int state) {
 	return allowTermination;
 }
 
+inline bool isPreProcessorEndTag(int state, int ch) {
+	const script_type type = ScriptOfState(state);
+	if (state == SCE_H_ASP || state == SCE_H_ASPAT || type == eScriptVBS || type == eScriptJS || type == eScriptPython) {
+		return ch == '%';
+	}
+	if (type == eScriptPHP) {
+		return ch == '%' || ch == '?';
+	}
+	return ch == '?';
+}
+
 // not really well done, since it's only comments that should lex the %> and <%
 inline bool isCommentASPState(int state) {
 	bool bResult;
@@ -1327,7 +1337,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 			case SCE_HJ_COMMENTDOC:
 			//case SCE_HJ_COMMENTLINE: // removed as this is a common thing done to hide
 			// the end of script marker from some JS interpreters.
-			case SCE_HB_COMMENTLINE:
+			//case SCE_HB_COMMENTLINE:
 			case SCE_HBA_COMMENTLINE:
 			case SCE_HJ_DOUBLESTRING:
 			case SCE_HJ_SINGLESTRING:
@@ -1345,7 +1355,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 			default :
 				// check if the closing tag is a script tag
 				if (const char *tag =
-						state == SCE_HJ_COMMENTLINE || isXml ? "script" :
+						(state == SCE_HJ_COMMENTLINE || state == SCE_HB_COMMENTLINE || isXml) ? "script" :
 						state == SCE_H_COMMENT ? "comment" : 0) {
 					Sci_Position j = i + 2;
 					int chr;
@@ -1635,7 +1645,7 @@ void SCI_METHOD LexerHTML::Lex(Sci_PositionU startPos, Sci_Position length, int
 		// handle the end of a pre-processor = Non-HTML
 		else if ((!isMako && !isDjango && ((inScriptType == eNonHtmlPreProc) || (inScriptType == eNonHtmlScriptPreProc)) &&
 				  (((scriptLanguage != eScriptNone) && stateAllowsTermination(state))) &&
-				  (((ch == '%') || (ch == '?')) && (chNext == '>'))) ||
+				  ((chNext == '>') && isPreProcessorEndTag(state, ch))) ||
 		         ((scriptLanguage == eScriptSGML) && (ch == '>') && (state != SCE_H_SGML_COMMENT))) {
 			if (state == SCE_H_ASPAT) {
 				aspScript = segIsScriptingIndicator(styler,
```

also LexHTML.cxx could be modernized with `nullptr`, `noexcept`, `constexpr` and `std::string_view`.

**Comment by zufuliu** [comment]
Above patch will break JSP comment (`SCE_H_XCCOMMENT`):
 ```jsp
<%-- comment --%>
```

[asp-comment-0720-2.patch](https://github.com/ScintillaOrg/lexilla/files/12107501/asp-comment-0720-2.patch)

**Comment by nyamatongwe** [comment]
~~~patch
+	if (state == SCE_H_ASP || state == SCE_H_ASPAT || type == eScriptVBS || type == eScriptJS || type == eScriptPython) {
~~~
Looks like a job for `AnyOf`.

**Comment by zufuliu** [comment]
OK, changed to `AnyOf`, patch for both #191 and #185.
[asp-comment-0721.patch](https://github.com/ScintillaOrg/lexilla/files/12122805/asp-comment-0721.patch)

**Comment by nyamatongwe** [comment]
> also LexHTML.cxx could be modernized with nullptr, noexcept, constexpr and std::string_view

Made some minor changes to avoid warnings with 5ffca56. constexpr would be OK for simple cases but have run into problems before with inconsistent use in standard library implementations.
