### ISSUE TITLE
[C++] Highlight escaped characters in C-strings literals 

### ISSUE THREAD

**Issue by ScienceDiscoverer** [ScintillaOrg/lexilla#190]
I think this is an important highlight feature that is still missing from lexilla. It allows to quickly spot string literal mistakes and overall makes string literals much more readable.

It is also important for C language lexer and any other lexers that use string literals with escape characters.

An example of how string literals should look like:

![chars_demo](https://github.com/ScintillaOrg/lexilla/assets/29157485/c7b8c92b-57df-4379-bbe0-58b8f5d7ba38)

**Comment by zufuliu** [comment]
Escape sequence is highlighted as `SCE_C_ESCAPESEQUENCE` after `lexer.cpp.escape.sequence` is set to 1.
https://github.com/ScintillaOrg/lexilla/blob/157f28ef9fe019558a572dd1532f9f63a9c2dd01/lexers/LexCPP.cxx#L413-L414
https://github.com/ScintillaOrg/lexilla/blob/157f28ef9fe019558a572dd1532f9f63a9c2dd01/lexers/LexCPP.cxx#L487-L489
