### ISSUE TITLE
PHP Numeric literals

### ISSUE THREAD

**Issue by nyamatongwe** [ScintillaOrg/lexilla#20]
On #19  @ivan-u7n commented:

I agree that the "HTML" lexer is rather complicated and needs overhaul. However, do you have in mind compile-time or run-time combining?

Nevertheless, I've prepared the update to PHP's numeric literals: [php-numbers.patch.txt](https://github.com/ScintillaOrg/lexilla/files/6874688/php-numbers.patch.txt). It's greedier than PHP's own lexer — it doesn't stop on the first invalid character, but goes on. It was made this way on purpose: to visually show, by applying the default style, the invalid “numeric words” which will result in parser errors.

The test for this patch (“+” denotes a valid syntax that should be styled as a number, “-” — an invalid one that should have the default style):
```php
123456; // +
123_456; // +
1234z6; // -
123456_; // -
123__456; // -

0x89Ab; // +
0x89_aB; // +
0x89zB; // -
0x89AB_; // -
0x_89AB; // -
0_x89AB; // -
0x89__AB; // -

1234.; // +
1234.e-0; // +
1234e+0; // +
1234e0; // +
1234.e-; // -
1234e+; // -
1234.-e; // -
1234+e; // -
1234e; // -

.1234; // +
.12e0; // +
.12.0e0; // -
.12e0.0; // -
.12e0e0; // -

1.234e-10; // +
1.2_34e-1_0; // +
1.234e-_10; // -
1.234e_-10; // -
1.234_e-10; // -
1._234e-10; // -
1_.234e-10; // -


01234567; // +
0_1234567; // +
012345678; // -

0...0; // +
```

_Originally posted by @ivan-u7n in https://github.com/ScintillaOrg/lexilla/issues/19#issuecomment-886275451_

**Comment by ivan-u7n** [comment]
It turned out that my earlier implementation was over zealous. [This one](https://github.com/ScintillaOrg/lexilla/files/6879898/php-numbers.patch.txt) seems to be less so. It still consumes as many word characters as it can, but its eagerness for operator characters is now strictly regulated.

The test
```php
123456; 123_456; // +
1234z6; 123456_; 123__456; // -

0x89Ab; 0x89_aB; // +
0x89zB; 0x89AB_; 0x_89AB; 0_x89AB; 0x89__AB; // -

1234.; 1234.e-0; 1234e+0; 1234e0; // +
1234.e-; 1234e+; 1234e; // -

.1234; .12e0; // +
.12.0e0; .12e0.0; .12e0e0; // -

1.234e-10; 1.2_34e-1_0; // +
1.234e-_10; 1.234e_-10; 1.234_e-10; 1._234e-10; 1_.234e-10; // -

01234567; 0_1234567; // +
012345678; // -

0...0; // 0. . .0
.0..0; // .0 . .0
0e+0+0e+0; // 0e+0 + 0e+0
```

**Comment by nyamatongwe** [comment]
Due to reevaluating octal numbers, `i` is reset and may count a following '/*' comment double for folding. This caused the `apostophe.php` test case to fail with this change, the fold level jumping from 401 to 403:
~~~
 2 400   0 + <?php
 0 401   0 | # Test that currently fails as comment style not started in a number.
 0 401   0 | # line-comment
 0 401   0 | // line-comment
 0 401   0 | /* comment */
 0 401   0 | $foo = 0#comment
 0 401   0 | $foo = 0//comment
 2 401   0 + $foo = 0/*'*/;
 0 403   0 | ?>
 1 403   0 | 
 0 403   0 | <br />
 0 403   0 | 
~~~

Rewinding is often a difficult strategy as there are multiple effects occurring in the code.

**Comment by nyamatongwe** [comment]
> I agree that the "HTML" lexer is rather complicated and needs overhaul. However, do you have in mind compile-time or run-time combining?

Sets of choices would be defined at compile time. At runtime an application may say they want to combine `ASP` and `C#` for server-side scripting along with `Mustache` and `Sass` then `Dart` client side. A limited number of slots (server-side-control, server-side-scripting; expression-language; stylesheet-language; client-side-language) would be specified at compile-time along with the choices available in each slot. The choice for each slot would be set by the application at runtime.

**Comment by ivan-u7n** [comment]
> Due to reevaluating octal numbers, `i` is reset and may count a following '/*' comment double for folding.

[The revised patch ](https://github.com/ScintillaOrg/lexilla/files/6883902/php-numbers.patch.txt) fixes it by using the inline reevaluation.

> Rewinding is often a difficult strategy as there are multiple effects occurring in the code.

I forgot that there are side-effects in the lex loop.

The patch also fixes the `apostophe.php` test case entirely by reusing the code in PHP's default branch, although it does so by using `goto`, which isn't liked by everybody. But this case seems perfect for this often misused language feature.

Here is how it might look like:
![image](https://user-images.githubusercontent.com/81974034/127123317-d708ee20-0827-45f3-aaef-352f98f81e26.png)

**Comment by nyamatongwe** [comment]
Issues and their fixes should be isolated. If the current `apostophe.php` case is incorrect then that should be a separate issue and fix.

LexerHTML::Lex is 1500 lines long and is worked on by many people so is a bad place to use a goto.

It should be possible to move the character handling logic for numeric literals out of Lex and into PhpNumberState.

**Comment by ivan-u7n** [comment]
Here is [the next iteration of my patch](https://github.com/ScintillaOrg/lexilla/files/6911901/php-numbers.patch.txt).

All character handling logic is moved into `PhpNumberState`. I also removed the usage of `goto`.

However the failing tests in `test/examples/hypertext/apostophe.php` still got fixed as a byproduct of using the look-ahead strategy in `PhpNumberState`.

The test case
```php
123456; 123_456; // +
1234z6; 123456_; 123__456; // -

0x89Ab; 0x89_aB; // +
0x89zB; 0x89AB_; 0x_89AB; 0_x89AB; 0x89__AB; // -

1234.; 1234.e-0; 1234e+0; 1234e0; 1234e0.PHP_EOL; // +
1234._; 1234.e-; 1234e+; 1234e; // -

.1234; .12e0; // +
.12.0e0; .12e0.0; .12e0e0; // -

1.234e-10; 1.2_34e-1_0; // +
1.234e-_10; 1.234e_-10; 1.234_e-10; 1._234e-10; 1_.234e-10; // -
1.234e-+10; 1.234e-_+10; // -

01234567; 0_1234567; // +
012345678; // -

0...0; // 0. . .0
.0..0; // .0 . .0
0e+0+0e+0; // 0e+0 + 0e+0

;0#comment
;0//comment
;0/*comment*/;
```
should render like
![image](https://user-images.githubusercontent.com/81974034/127753727-bc5b282c-794c-49a8-8cbc-a9314aaa6c18.png)

PS. I think, I'll open another issue for the hypertext-lexer-overhaul discussion after I think it through, for I have some ideas but I'm not sure whether they are implementable.

**Comment by nyamatongwe** [comment]
Committed with reformatting. LexHTML.cxx follows [1TBS](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_(OTBS)) as does most of Lexilla and Scintilla. Changes should match existing code. Also fixed spelling of "unchanged".
