### ISSUE TITLE
Inconsistent lexing of '-' at line start by bash lexer

### ISSUE THREAD

**Issue by nyamatongwe** [ScintillaOrg/lexilla#202]
The following text is lexed inconsistently by the `bash` lexer with `-a` as different styles [7,8] and `-b` as [8,8] where `7=SCE_SH_OPERATOR` and `8=SCE_SH_IDENTIFIER`.
~~~bash
-a
#
-b
#
~~~

Styles will be applied differently depending on where a lex starts: add a character to the comment on line 4 (after `-b`) and `-b` will change to have two styles.

This is caused by the test `IsASpace(sc.chPrev)` in 'test operator or short and long option' since `sc.chPrev` is initialized to 0 instead of to the character before the start of lexing.

The constructor of `StyleContext` can be changed to initialize `chPrev` to the preceding character (often '\n') with this patch.
~~~patch
--- a/lexlib/StyleContext.cxx
+++ b/lexlib/StyleContext.cxx
@@ -40,6 +40,8 @@ StyleContext::StyleContext(Sci_PositionU startPos, Sci_PositionU length,
 	styler.StartAt(startPos /*, chMask*/);
 	styler.StartSegment(startPos);
 
+	chPrev = GetRelativeCharacter(-1);
+
 	// Variable width is now 0 so GetNextChar gets the char at currentPos into chNext/widthNext
 	GetNextChar();
 	ch = chNext;
~~~

However, that doesn't fix the `-a` at the start of file as there is no preceding '\n' to place in `chPrev`. There could be a pretend '\n' before the file start but that is likely to be unexpected. It would also be unusual to treat '\0' as a space in `IsASpace`. To fix the file start case, an additional clause can be added.
~~~patch
--- a/lexers/LexBash.cxx
+++ b/lexers/LexBash.cxx
@@ -1092,7 +1092,7 @@ void SCI_METHOD LexerBash::Lex(Sci_PositionU startPos, Sci_Position length, int
 			} else if (sc.ch == '-' && // test operator or short and long option
 					   cmdState != CmdState::Arithmetic &&
 					   (IsUpperOrLowerCase(sc.chNext) || sc.chNext == '-') &&
-					   IsASpace(sc.chPrev)) {
+					   ((sc.chPrev == 0) || IsASpace(sc.chPrev))) {
 				sc.SetState(SCE_SH_WORD | insideCommand);
 				sc.Forward();
 			} else if (setBashOperator.Contains(sc.ch)) {
~~~

Patch 2 supersedes the need for patch 1 but its likely safer to make both changes for more stable lexing of unexpected cases.

**Comment by zufuliu** [comment]
The change for `IsASpace(sc.chPrev)` can be updated to use `IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev)` (similar to `const bool keywordEnds =`), this will fix `-a|-b)`  inside case clause.

**Comment by zufuliu** [comment]
`sc.chPrev == '#'` can be added to fix `option=--help`.
Maybe the check for `sc.chPrev` can be removed? so outside arithmetic expression, `--`  and `-alpha` is always treated as identifier.

**Comment by nyamatongwe** [comment]
> ... `#` can be added to fix `option=--help`.

I don't understand since `#` isn't involved. Perhaps that should be `=`?

Checking `sc.chPrev` started with
https://sourceforge.net/p/scintilla/bugs/496/
https://sourceforge.net/p/scintilla/code/ci/bba709f5a31fa32db03874416237458b23d9b446/

**Comment by zufuliu** [comment]
A more complete test for dash highlighting:
```bash
declare -A optionSet=([--help]=0)
for option in {-h,--help,--version,--verbose}; do
case $option in
	-h|--help)
		optionSet[--help]=1
		echo help: $option
		;;
	-*-version)
		echo version: $option
		;;
	-*[-a-zA-Z0-9])
		echo other: $option
		;;
esac
done

option=--help
[[ $option == *-h* ]] && echo $option=${optionSet[$option]}
```

The fix for bug 496 is to ensure `-` at word start (after white space or meta character). patch to treat `--` and `-alpha` as identifier outside arithmetic expression:
[bash-dash-0905.patch](https://github.com/ScintillaOrg/lexilla/files/12522186/bash-dash-0905.patch)
```diff
diff --git a/lexers/LexBash.cxx b/lexers/LexBash.cxx
index d853ce68..b8609d5b 100644
--- a/lexers/LexBash.cxx
+++ b/lexers/LexBash.cxx
@@ -1093,10 +1094,12 @@ void SCI_METHOD LexerBash::Lex(Sci_PositionU startPos, Sci_Position length, int
 				}
 			} else if (sc.ch == '-' && // test operator or short and long option
 					   cmdState != CmdState::Arithmetic &&
-					   (IsUpperOrLowerCase(sc.chNext) || sc.chNext == '-') &&
-					   (IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev))) {
-				sc.SetState(SCE_SH_WORD | insideCommand);
-				sc.Forward();
+					   (IsUpperOrLowerCase(sc.chNext) || sc.chNext == '-')) {
+				if (IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev)) {
+					sc.SetState(SCE_SH_WORD | insideCommand);
+				} else {
+					sc.SetState(SCE_SH_IDENTIFIER | insideCommand);
+				}
 			} else if (setBashOperator.Contains(sc.ch)) {
 				bool isCmdDelim = false;
 				sc.SetState(SCE_SH_OPERATOR | insideCommand);
```

`-*` still highlighted as operator. maybe the restrict for `sc.chNext` can also be removed:
```bash
for gcc in gcc{,-8,-9,-1{0..4}}; do
	echo $gcc
done
```

**Comment by zufuliu** [comment]
> maybe the restrict for `sc.chNext` can also be removed:

Or relaxed to `!IsADigit(sc.chNext)`.

**Comment by zufuliu** [comment]
Updated patch to use ` !IsADigit(sc.chNext)`.
[bash-dash-0906.patch](https://github.com/ScintillaOrg/lexilla/files/12528869/bash-dash-0906.patch)
```diff
diff --git a/lexers/LexBash.cxx b/lexers/LexBash.cxx
index 647cc262..0dde14c7 100644
--- a/lexers/LexBash.cxx
+++ b/lexers/LexBash.cxx
@@ -1094,10 +1094,12 @@ void SCI_METHOD LexerBash::Lex(Sci_PositionU startPos, Sci_Position length, int
 				}
 			} else if (sc.ch == '-' && // test operator or short and long option
 					   cmdState != CmdState::Arithmetic &&
-					   (IsUpperOrLowerCase(sc.chNext) || sc.chNext == '-') &&
-					   (IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev))) {
-				sc.SetState(SCE_SH_WORD | insideCommand);
-				sc.Forward();
+					   !IsADigit(sc.chNext)) {
+				if (IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev)) {
+					sc.SetState(SCE_SH_WORD | insideCommand);
+				} else {
+					sc.SetState(SCE_SH_IDENTIFIER | insideCommand);
+				}
 			} else if (setBashOperator.Contains(sc.ch)) {
 				bool isCmdDelim = false;
 				sc.SetState(SCE_SH_OPERATOR | insideCommand);
```

equivalent test cases for negative number (not sure what first `-1` is).
```bash
for gcc in gcc{,-1{4..0..-1}}; do
	echo $gcc
done

for gcc in gcc{,{-14..-10}}; do
	echo $gcc
done
```

**Comment by zufuliu** [comment]
Updated test case, I think bash-dash-0906.patch (treat dash as identifier except inside arithmetic expression or immediately before a number) is ready.
```bash
declare -A optionSet=([--help]=0)
for option in {-h,--help,--version,--verbose,-,--}; do
case $option in
	-h|--help)
		optionSet[--help]=1
		echo help: $option
		;;
	-*-version)
		echo version: $option
		;;
	--)
		echo stop
		;;
	-)
		echo stdin
		;;
	-*[-a-zA-Z0-9])
		echo other: $option
		;;
esac
done

option=--help
[[ $option == *-h* ]] && echo $option=${optionSet[$option]}

for gcc in gcc{,-1{4..0..-1}}; do
	echo $gcc
done

for gcc in gcc{,{-14..-10}}; do
	echo $gcc
done
```

**Comment by zufuliu** [comment]
`~-` is tilde-prefix, https://www.gnu.org/software/bash/manual/bash.html#Tilde-Expansion
```
~+/foo
~-/foo
```

[bash-dash-0907.patch](https://github.com/ScintillaOrg/lexilla/files/12543105/bash-dash-0907.patch)
```diff
diff --git a/lexers/LexBash.cxx b/lexers/LexBash.cxx
index 647cc262..87443e81 100644
--- a/lexers/LexBash.cxx
+++ b/lexers/LexBash.cxx
@@ -1094,10 +1094,12 @@ void SCI_METHOD LexerBash::Lex(Sci_PositionU startPos, Sci_Position length, int
 				}
 			} else if (sc.ch == '-' && // test operator or short and long option
 					   cmdState != CmdState::Arithmetic &&
-					   (IsUpperOrLowerCase(sc.chNext) || sc.chNext == '-') &&
-					   (IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev))) {
-				sc.SetState(SCE_SH_WORD | insideCommand);
-				sc.Forward();
+					   sc.chPrev != '~' && !IsADigit(sc.chNext)) {
+				if (IsASpace(sc.chPrev) || setMetaCharacter.Contains(sc.chPrev)) {
+					sc.SetState(SCE_SH_WORD | insideCommand);
+				} else {
+					sc.SetState(SCE_SH_IDENTIFIER | insideCommand);
+				}
 			} else if (setBashOperator.Contains(sc.ch)) {
 				bool isCmdDelim = false;
 				sc.SetState(SCE_SH_OPERATOR | insideCommand);
```
