### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [ScintillaOrg/lexilla#217]
lexers/LexTACL.cxx line 188
Code:
	if (isTACLwordstart(ch)) {
				ColourTo(styler, i-1, state, bInAsm);
				state = SCE_C_IDENTIFIER;
			} else if (ch == '{') {  // <-- covers the next two else if 
				ColourTo(styler, i-1, state, bInAsm);
				state = SCE_C_COMMENT;
			} else if (ch == '{' && chNext == '*') {
				ColourTo(styler, i-1, state, bInAsm);
				state = SCE_C_COMMENTDOC;
			} else if (ch == '=' && chNext == '=') {
				ColourTo(styler, i-1, state, bInAsm);
				state = SCE_C_COMMENTLINE;
			} else if (ch == '"') {

**Comment by nyamatongwe** [comment]
Do you use TACL?

Its not worth modifying lexers that are rarely used, have no tests and no maintainer.
