### ISSUE TITLE
Feature Request: Folding by indentation in plain text

### ISSUE THREAD

**Issue by ghost** [ScintillaOrg/lexilla#218]
I often take very-long notes. So "folding by indentation in plain text" is a very useful feature.

After studing in long time, I found that many people also need it.
Specially, notepad2 supported it. It should only change a file: LexNull.cxx
https://github.com/zufuliu/notepad2/blob/main/scintilla/lexers/LexNull.cxx

Could anyone please review and update the feature?

Thank you very much.

Refer: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14465

**Comment by zufuliu** [comment]
Notepad++ can use https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexIndent.cxx, which is same as notepad2's LexNull.cxx except empty line handing differences see https://sourceforge.net/p/scintilla/bugs/1932/ and https://sourceforge.net/p/scintilla/feature-requests/1174/

SciTE also uses LexIndent.cxx:
![image](https://github.com/ScintillaOrg/lexilla/assets/2289926/29f27fc5-d517-468b-b1d6-925f8547ac8e)

**Comment by nyamatongwe** [comment]
Support questions should go to the Scintilla interest mailing list at
https://groups.google.com/forum/#!forum/scintilla-interest

This tracker is for issues, commonly bugs or new code.

Replying to an issue that has been closed in unlikely to be seen by many people as the standard issue list page excludes closed issues.
