### ISSUE TITLE
Incorrect PHP word end detection

### ISSUE THREAD

**Issue by ivan-u7n** [ScintillaOrg/lexilla#22]
The first line of the `SCE_HPHP_WORD` case should be 
```c++
if (!IsPhpWordChar(ch)) {
```
instead of the current
```c++
if (!IsAWordChar(ch)) {
```
as otherwise things like `__FILE__.':'.__LINE__` are parsed incorrectly — the first word isn't recognized as a keyword due to the dot being the part of it. Moreover something like `__FILE__.__LINE__` is considered a single word with no operators within.

**Comment by nyamatongwe** [comment]
Committed fix.
