### ISSUE TITLE
Batch Syntax "keyword" + ":" => "keyword:" dont work properly

### ISSUE THREAD

**Issue by GabrielFrigo4** [ScintillaOrg/lexilla#222]
In the .bat file, when I add a colon ":" right after a keyword => "keyword:', that keyword loses its highlighting, which was not supposed to happen. Furthermore, when I have a word before a function ":function_name" => "word :function_name", the function also loses its highlighting, and that was not expected behavior either

NOTE1: When a ":function_name" appears in the code between double quotes, it is not highlighted, which is the expected behavior.
NOTE2: I know that notepad++ != Lexilla. However, notepad++ uses Lexilla, so to fix this behavior in notepad++ you have to fix it in Lexilla

![image](https://github.com/ScintillaOrg/lexilla/assets/66432268/0276161f-574e-4809-a6ff-91ef8809f9b3)

**Comment by mpheath** [comment]
> NOTE1: When a ":function_name" appears in the code between double quotes, it is not highlighted, which is the expected behavior.

Not aware of any issue with labels in quotes and I cannot consider why a label would be highlighted in quotes. So I have not done anything about it and not sure if I want to do more than necessary.

Before and after fix displayed in SciTE.
![keyswords_with_colon](https://github.com/ScintillaOrg/lexilla/assets/58158242/40677c6a-20e2-4f53-85a8-5dba7359f658)

[Issue222.bat.zip](https://github.com/ScintillaOrg/lexilla/files/13817753/Issue222.bat.zip)

**Comment by GabrielFrigo4** [comment]
> > NOTE1: When a ":function_name" appears in the code between double quotes, it is not highlighted, which is the expected behavior.
> 
> Not aware of any issue with labels in quotes and I cannot consider why a label would be highlighted in quotes. So I have not done anything about it and not sure if I want to do more than necessary.
> 
> Before and after fix displayed in SciTE. ![keyswords_with_colon](https://private-user-images.githubusercontent.com/58158242/293883478-40677c6a-20e2-4f53-85a8-5dba7359f658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTY2NTAsIm5iZiI6MTcwNDI5NjM1MCwicGF0aCI6Ii81ODE1ODI0Mi8yOTM4ODM0NzgtNDA2NzdjNmEtMjBlMi00ZjUzLTg1YTgtNWRiYTczNTlmNjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE1MzkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjUzY2EyMTM3OTg1NTI3NGE3MDQzN2M5Y2ExMDVkN2IwNjBmODYzNDk2ZWYxMGJkZjczNGQzN2QzYzM1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.erlhWN8FT2rbuznTE2En3NA2Cy4QQlJqhI2cexbPDn8)
> 
> [Issue222.bat.zip](https://github.com/ScintillaOrg/lexilla/files/13817753/Issue222.bat.zip)

The correction is perfect.
Regarding NOTE1, I think I expressed myself wrong, as it is not supposed to highlight functions in quotation marks.  I just wanted to make it clear that this was not supposed to change with this fix :)

**Comment by nyamatongwe** [comment]
Why is this patch styling `goto` targets in `SCE_BAT_COMMAND` as if they were commands? There is a difference in the current lexer between `goto` and `call` but that is OK since `call` runs an external file command and `goto` is just internal flow control.

**Comment by mpheath** [comment]
@GabrielFrigo4 Keywords may look good. What follows the keywords is questionable. Thanks for the reply to clarify NOTE1.

@nyamatongwe `call` can be passed both an external command or a label as the label is recognized by the colon. It certainly is debatable about which direction to go with it as being command style or label as default style. Either go with command style or try to prevent it and use default style if a label. And `goto` followed the same logic as the decision as made with `call`. Some objection was expected about my decision and perhaps should be done the other way.

`goto` is always followed by label or sometimes I have seen `(goto)` with no label which IIRC alters the stack, which the latter seems OK as it terminates at `)`. `goto` might be easier to fix than `call` which as mentioned can be followed by label or command so might need special handling.

I'll try the other way of striving for default styling for label and see what can come up with. Might take alittle while as I have some other matters to attend to first. I may need to allocate more time into the other way as it might need more attention to correct the styling.

<details>
<summary>Test Gtihub styling:</summary>

```bat
call file.bat
call "file.bat"
call :label
goto :label
goto label
echo: %var%
echo: text
echo text
(goto)
```

and for those who cannot locate the spacebar:

```bat
call:label
goto:label
echo:%var%
echo:text
```
and to consider that colon is not needed for `label` after `goto` makes this invalid:
```bat
gotolabel
```

Seems worse with `label` styled as keyword. `(goto)` incorrect style. LexBatch has no string style to compare evenly and Github seems missing a command style so uses a default style unless quoted. Little inspiration there. LexBatch might be able to do better.
</details>

**Comment by mpheath** [comment]
Version 2.

This might be less colourful for labels, though the keywords are fixed. IMO it is more technically correct.

 * `call` can handle internal commands, external commands and labels.
 * A label is not a command so it should never have been styled as a command previously after `goto` or `call`.

Perhaps thoughts are I am be too much the other way. Consider that people claim that a called label is a [function or subroutine]. CMD with `goto` or `call`, stops and goes to the label and continues execution. The difference is that `call` processes arguments and returns back to the position of the caller. I see no clear evidence that a label can be a command.

Before and after fix displayed in SciTE.
![keyswords_with_colon2](https://github.com/ScintillaOrg/lexilla/assets/58158242/6f496165-e661-4cfc-9d8d-13b2d68c60da)

[Issue222_v2.zip](https://github.com/ScintillaOrg/lexilla/files/13830268/Issue222_v2.zip)

[function or subroutine]: https://en.wikipedia.org/wiki/Function_(computer_programming)
