### ISSUE TITLE
raw formatted string is not handled in Python lexer

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#223]
`rf` and `fr`, etc. are listed at https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
```
stringprefix    ::=  "r" | "u" | "R" | "U" | "f" | "F"
                     | "fr" | "Fr" | "fR" | "FR" | "rf" | "rF" | "Rf" | "RF"
```

```python
name = 'notepad'
print(rf'C:\Windows\{name}.exe')
print(fr'C:\Windows\{name}.exe')

```

**Comment by nyamatongwe** [comment]
This is the case for `rf` but `fr` works due to test ordering.

![RawFormattedPython](https://github.com/ScintillaOrg/lexilla/assets/225818/250ce577-1a0b-491c-be30-82365765cd5b)

**Comment by zufuliu** [comment]
Current Python lexer doesn't distinguish between raw and normal string/bytes.

I'm not working on this, cc @jpe.

**Comment by nyamatongwe** [comment]
A potential patch but it's large for the small problem its addressing.

[RawFormatted.patch](https://github.com/ScintillaOrg/lexilla/files/13999013/RawFormatted.patch)

**Comment by jpe** [comment]
It should be a small change; I'll try to look at this in the next few days.

**Comment by jpe** [comment]
I created a pull request with a commit to fix this: https://github.com/ScintillaOrg/lexilla/pull/227
