### ISSUE TITLE
Rust: raw identifiers are marked as errors.

### ISSUE THREAD

**Issue by Ekopalypse** [ScintillaOrg/lexilla#239]
```
fn main() {
    let r#true = false;
    println!("{}", r#true);
}
```

![image](https://github.com/ScintillaOrg/lexilla/assets/47723516/41deed98-ee1c-4e51-a173-c39de4d6ebf1)

**Comment by nyamatongwe** [comment]
Explanation of raw identifiers: https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html.
