### ISSUE TITLE
F#: Highlight `printf` specifiers in type-checked interpolated strings (.NET 5 feature)

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#24]
_Follows #21_

Lexilla (correctly) ignores `printf` specifiers inside malformed interpolated strings:

![pre-patch-fmt-specs](https://user-images.githubusercontent.com/59004801/129416947-63a083e5-96b3-4728-9175-7cf6f1825eb8.png)

But that's the incidental result of a blanket restriction:

https://github.com/ScintillaOrg/lexilla/blob/68ff521b53fac828d07d234d330321cfec74699d/lexers/LexFSharp.cxx#L499-L500

And it overlooks valid exceptions, like escaped percent signs:

~~~
> $"%% decrease: -{0.2 * 100.}%%" ;;
val it : string = "% decrease: -20%"
~~~

Moreover, since F# 5.0, every kind of `printf` specifier is allowed inside interpolated strings, provided:

1. they occur right before [the braces around the interpolated value][]:

~~~
> $"%.2f{5./2.}" ;;
val it : string = "2.50"

> $"%.2f {5./2.}" ;;

  $"%.2f {5./2.}" ;;
  ^^^^^^^^^^^^^^^

stdin(2,1): error FS3376: Invalid interpolated string. Interpolated strings may not use '%' format specifiers unless each is given an expression, e.g. '%d{1+1}'.
~~~

2. the expression evaluates to the same type as the given format:

~~~
> $"%d{5./2.}" ;;

  $"%d{5./2.}" ;;
  --------^^

stdin(3,9): error FS0001: The type 'float' is not compatible with any of the types byte,int16,int32,int64,sbyte,uint16,uint32,uint64,nativeint,unativeint, arising from the use of a printf-style format string
~~~

These patches update the lexing rules for `printf` specifiers to include interpolated strings, when they contian: 

i) escaped percent signs, at any position
ii) valid type annotations, as illustrated in context 1

[LexFSharp-PrintfSpecsInNet5Strs.zip](https://github.com/ScintillaOrg/lexilla/files/6985161/LexFSharp-PrintfSpecsInNet5Strs.zip)

[the braces around the interpolated value]: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/interpolated-strings#typed-interpolated-strings

**Comment by nyamatongwe** [comment]
Fix committed.
