### ISSUE TITLE
Add single file input for compiler in lexilla.mak

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [ScintillaOrg/lexilla#244]
Currently in the [lexilla.mak](https://github.com/ScintillaOrg/lexilla/blob/master/src/lexilla.mak) file there is one call to compiler with all files. This causes some caching tools to be unable to handle such compilation (like Ccache/Sccache ). They expect to pass only one file to the compiler. The problem does not occur with the [makefile ](https://github.com/ScintillaOrg/lexilla/blob/master/src/makefile) file.

Is there any chance to add single file support to the current  [lexilla.mak](https://github.com/ScintillaOrg/lexilla/blob/master/src/lexilla.mak) (as an option) or to add a separate file that will provide such support? 
The same problem also occurs for Scintilla.

**Comment by nyamatongwe** [comment]
Batching input to the Microsoft C++ compiler and allowing it to internally multi-process with `/MP` improves compilation speed. Its contrary to gcc where breaking the build up into individual files and allowing make to multi-process is commonly faster. `lexilla.mak` is processed by nmake which doesn't have an equivalent to GNU make's `--jobs` argument.

**Comment by nyamatongwe** [comment]
Switching the 3 batch inference rules to standard inference rules breaks the compilation into individual files. It can be done by replacing their terminating `::` with `:`.
~~~makefile
{..\lexlib}.cxx{$(DIR_O)}.obj:
	$(CXX) $(CXXFLAGS) -c $(NAME)$(DIR_O)\ $<
{..\lexers}.cxx{$(DIR_O)}.obj:
	$(CXX) $(CXXFLAGS) -c $(NAME)$(DIR_O)\ $<
{.}.cxx{$(DIR_O)}.obj:
	$(CXX) $(CXXFLAGS) -c $(NAME)$(DIR_O)\ $<
~~~

Running this takes more time than batch rules - for me, 45 seconds debug build compared to 14.

**Comment by ArkadiuszMichalski** [comment]
@nyamatongwe Thanks for the tip, I didn't know it could be forced in such a trivial way. It would be nice if this could be enforced through some variable added in the original Scintilla/Lexilla `.mak` files (like in [MS example](https://learn.microsoft.com/en-us/cpp/build/reference/inference-rules?view=msvc-170#-batch-mode-rules)), but if you don't want additional modifications we can always slightly modify these files before calling it.

>Running this takes more time than batch rules - for me, 45 seconds debug build compared to 14.

Yes, it will be slower, but assuming occasional changes and the use of some caching tool it might be acceptable.

Combined with Ccache and nmake/cl and GitHub Action it doesn't look that great (much worse than with make/GCC).
- with batch mode and without Ccache build takes 30-60s (Scintilla), 30-40s (Lexilla), [sample log](https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/8888349320/job/24405037727).
- without batch mode and with Ccache build takes 30-50s (Scintilla), 16-20s (Lexilla), [sample log](https://github.com/ArkadiuszMichalski/notepad-plus-plus/actions/runs/8904786847/job/24454577867).

I don't know why the improvement for Scintilla is so small, sometimes it can be even slower than without using Ccache. This requires a more detailed analysis of whether anything can be improved in the case of no batch mode.

**Comment by nyamatongwe** [comment]
Even more trivial way: the "/Y" option to nmake:
> /Y | Disables batch-mode inference rules. When this option is selected, all batch-mode inference rules are treated as regular inference rules.

https://learn.microsoft.com/en-us/cpp/build/reference/running-nmake?view=msvc-170#nmake-options

**Comment by nyamatongwe** [comment]
Closing as desired result can be easily achieved.
