### ISSUE TITLE
 Add User-defined keywords in HTML

### ISSUE THREAD

**Issue by DomOBU** [ScintillaOrg/lexilla#246]
Hello,

I use Notepad++.
This software uses Lexilla.

In Notepad++, it is possible for CSS and JS to define "User-defined keywords" for certain styles.

For HTML, this feature does not exist. The moderator of the Notepadd++ site tells me that this is a Lexilla limitation.
Are there any plans to add this functionality for HTML in Lexilla ?
This would be a major step forward and would ensure that Notepad++ does not lag behind other web-oriented source code software.

**Comment by nyamatongwe** [comment]
Recent release 5.3.2 included:
> HTML: Implement substyles for tags, attributes, and identifiers SCE_H_TAG, SCE_H_ATTRIBUTE, SCE_HJ_WORD, SCE_HJA_WORD, SCE_HB_WORD, SCE_HP_WORD, SCE_HPHP_WORD.
HTML: Implement context-sensitive attributes. "tag.attribute" matches "attribute" only inside "tag".

**Comment by mpheath** [comment]
What is "Default keywords" and "User-defined keywords"? It is a Notepad++ feature that joins 2 keyword lists into 1 keyword list to be passed on to Lexilla.

This image is `C++` styling for `INSTRUCTION WORD` in Notepad++'s Style Configurator.

![npp_userdefinedkeywords](https://github.com/ScintillaOrg/lexilla/assets/58158242/4f17f936-baf7-41ad-89e8-9f4c02990828)

HTML does not have "Default keywords" and "User-defined keywords" anywhere available in Notepad++'s Style Configurator. This is not a limitation of Lexilla, rather an incomplete feature of Notepad++ regarding HTML.

IMO, this issue does not belong here. It started in a Notepad++ forum [post] and is an issue related to Notepad++.

 [post]: https://community.notepad-plus-plus.org/topic/25741/html-user-defined-keywords/6

**Comment by nyamatongwe** [comment]
Closing as appears to really be a Notepad++ issue.
