### ISSUE TITLE
Missing shebang support in JavaScript

### ISSUE THREAD

**Issue by ghost** [ScintillaOrg/lexilla#253]
I don't have much to say, another user previously reported this in detail in the Notepad++ directory, which uses Lexilla:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14706

**References:**

1. Official specification used by JavaScript, ECMA-262. (begin of page 11 of the PDF)
https://ecma-international.org/wp-content/uploads/ECMA-262_14th_edition_june_2023.pdf
2. W3Schools. (scroll down the article)
https://www.w3schools.com/js/js_2023.asp

**Comment by zufuliu** [comment]
A simple change is following (`#!` has no valid meaning in all C/C++ like languages):
```diff
diff --git a/lexers/LexCPP.cxx b/lexers/LexCPP.cxx
index f5ab166c..15255785 100644
--- a/lexers/LexCPP.cxx
+++ b/lexers/LexCPP.cxx
@@ -850,6 +850,10 @@ void SCI_METHOD LexerCPP::Lex(Sci_PositionU startPos, Sci_Position length, int i
 		if (MaskActive(styler.StyleAt(back)) == SCE_C_OPERATOR) {
 			chPrevNonWhite = styler.SafeGetCharAt(back);
 		}
+	} else if (sc.Match('#', '!')) {
+		// Shell Shebang at beginning of file
+		sc.SetState(SCE_C_COMMENTLINE);
+		sc.Forward();
 	}
 
 	StyleContext sc(startPos, length, initStyle, styler);
```
