### ISSUE TITLE
[HTML] JavaScript highlighting bugs

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#273]
1. `// Eat the * so it isn't used for the end of the comment` can be simplified as PHP's `i++;`, since code folding is same.
https://github.com/ScintillaOrg/lexilla/blob/81a84bd4169d3c27947d2af15d2c126fca85be75/lexers/LexHTML.cxx#L2204-L2207
https://github.com/ScintillaOrg/lexilla/blob/81a84bd4169d3c27947d2af15d2c126fca85be75/lexers/LexHTML.cxx#L2650-L2653

Also, it's missing from 
https://github.com/ScintillaOrg/lexilla/blob/81a84bd4169d3c27947d2af15d2c126fca85be75/lexers/LexHTML.cxx#L2243-L2249
https://github.com/ScintillaOrg/lexilla/blob/81a84bd4169d3c27947d2af15d2c126fca85be75/lexers/LexHTML.cxx#L2706-L2711

2. `SCE_HJ_REGEX` and `SCE_HJA_REGEX` can be added into `isStringState()`, e.g. treat regex as string quoted by `/`.
https://github.com/ScintillaOrg/lexilla/blob/81a84bd4169d3c27947d2af15d2c126fca85be75/lexers/LexHTML.cxx#L176-L179

3. `SCE_HJ_COMMENTDOC` and `SCE_HJA_COMMENTDOC` are missing from `IsScriptCommentState()`
https://github.com/ScintillaOrg/lexilla/blob/81a84bd4169d3c27947d2af15d2c126fca85be75/lexers/LexHTML.cxx#L513-L516

**Comment by nyamatongwe** [comment]
It is unclear what problems are being addressed here.

**Comment by zufuliu** [comment]
> It is unclear what problems are being addressed here.

```html
<script>
var/**/pi=3.14/**/; /**/;
/*
<?xml>
*/
/**
<?xml>
*/
/<?xml/.test('<?xml');
</script>
```

line 2 test missing `i++` for JavaScript block comment.
line 6-8 test `IsScriptCommentState()`.
fix for line 10 requires extra change from issue #269, but I think it's good to treat regex as string like style.

Before fix:
![image](https://github.com/user-attachments/assets/880480ff-03d1-4bbb-bd43-e7a7aff5edc3)

After fix:
![image](https://github.com/user-attachments/assets/7c7b923b-857b-4b4b-b2bd-72a5e875f5bd)

[HTNL-JavaScript-0909.patch](https://github.com/user-attachments/files/16928916/HTNL-JavaScript-0909.patch)

**Comment by zufuliu** [comment]
Updated test file:
```html
<script>
var pi/*/=3.1415/*/=3.14;
/*
<?xml>
<!doctype>
*/
/**
<?xml>
<!doctype>
*/
/<?xml>/.test('<?xml>');
/<!doctype>/.test("<!doctype>");
</script>
```

Before:
![image](https://github.com/user-attachments/assets/d6261f2b-a092-4909-8ef8-d440535f966a)

After:
![image](https://github.com/user-attachments/assets/37932cbf-ec70-40ad-811d-ff0a9ea868b0)
