### ISSUE TITLE
Doesn't seem to compile properly by GCC9.5.0 

### ISSUE THREAD

**Issue by arrosev** [ScintillaOrg/lexilla#278]
The version of gcc I use: gcc version 9.5.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders),
Error: g++: error: unrecognized command line option '--std=c++20'; did you mean '--std=c++2a'?

**Comment by nyamatongwe** [comment]
Lexilla does not use '--std=c++20'. Can you reveal which particular command you used to build?

Perhaps you were building SciTE which is a separate project that requires a newer version of gcc. gcc 13.x is known to work.

**Comment by arrosev** [comment]
Yes, my mistake. I updated GCC and now it compiles SciTE correctly, thanks for the reply!
