### ISSUE TITLE
Add missing repositories?

### ISSUE THREAD

**Issue by Neustradamus** [ScintillaOrg/lexilla#291]
Dear @ScintillaOrg team,

Can you add missing repositories into this organization?

Thanks in advance.

**Comment by nyamatongwe** [comment]
Which repositories are you referring to?

**Comment by Neustradamus** [comment]
@nyamatongwe: Currently, there is only "lexilla":
- https://github.com/ScintillaOrg

**Comment by nyamatongwe** [comment]
Yes, lexilla is the only repository. As I asked: which repositories are you referring to?

**Comment by rdipardo** [comment]
@Neustradamus, in case it anwsers your question, Mitchell Foral maintains [a git mirror](https://github.com/orbitalquark/scintilla-mirror) of Scintilla's mercurial repository which is updated daily:

    git clone --branch default https://github.com/orbitalquark/scintilla-mirror.git

**Comment by nyamatongwe** [comment]
Closing as there is nothing to do here.

**Comment by Neustradamus** [comment]
Dear @ScintillaOrg, @moltenform,

Can you transfer into this organization:
- https://github.com/moltenform/scite-files

Thanks in advance.

**Comment by nyamatongwe** [comment]
> Can you transfer into this organization:

The purpose of [scite-files](https://github.com/moltenform/scite-files) is to hold additional files for use by SciTE to allow them to develop independently of SciTE core files.

The home of Scintilla and SciTE is SourceForge, not GitHub.
https://sourceforge.net/projects/scintilla/
