### ISSUE TITLE
Proposal: Extension of lexer protocol

### ISSUE THREAD

**Issue by HoTschir** [ScintillaOrg/lexilla#296]
Beside to function `GetLibraryPropertyNames`, please make available similar functions to get some kind of *named styles* and *named keywordlists*. Functions should provide lists of name beside the index. Style indices could be derived from `LexicalStyle.iface` definitions.

Explanation:
Keywordlists and styles are configurable by using so called config files, e.g for SciTE `cpp.properties` is such a file, for geany, which is also based on Lexilla, the corresponding file is `filetypes.cpp`.

Until now, there is the problem, either the user of app (SciTE, geany,..) has to struggle with unmeaning numbers in configuration files (cpp.properties: `keywords3` `style.cpp.3`) or developer of application troublesomely has manually map numbers to meaningful names (filetypes.cpp: `commentdoc`) **and keep it updated**. Each of them is a drawback in my eyes.

The suggested functions can help to match the names to the numbers and keep them up to date.

Conglusion:
To use names in place of numbers is catchy for developer of editor application Lexilla is used for, as well as user of this application, when editing configuration files.

**Comment by nyamatongwe** [comment]
For the lexers that have this implemented, instantiate an `ILexer5` then `NamedStyles`, `NameOfStyle` and `DescribeWordListSets`. Otherwise, use the results from `scripts\LexillaData.py` at build time.

**Comment by HoTschir** [comment]
> For the lexers that have this implemented, instantiate an `ILexer5` then `NamedStyles`, `NameOfStyle` and `DescribeWordListSets`. Otherwise, use the results from `scripts/LexillaData.py` at build time.

Got it in source of LexCPP and LexVisualProlog and learn, how it works. Thanks for your reply.
