### ISSUE TITLE
Rust: 128-bit integer literals are not parsed correctly

### ISSUE THREAD

**Issue by LordHavelockVetinari** [ScintillaOrg/lexilla#33]
The code which parses integer suffixes recognizes the suffixes: `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64`, `usize` and `isize`, but not `u128` and `i128`, so integer literals like `10u128` or `0xffffi128` are marked as errors.
https://github.com/ScintillaOrg/lexilla/blob/782725aeed8db061e41fe14971887188380481b3/lexers/LexRust.cxx#L272-L293

**Comment by nyamatongwe** [comment]
Fix committed.
