### ISSUE TITLE
Rust: Document length exceeded when file ends with unterminated block comment

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#35]
`LexRust` can pass an invalid position to `LexAccessor::ColourTo` when a file ends with /*, causing [this debug assertion] to fail:

```cpp
         assert((startPosStyling + validLen) < Length());
```

![unpatched-trailing-block-comm](https://user-images.githubusercontent.com/59004801/137476730-6c71ee43-e624-4cfb-bbe5-8bf27654318e.png)

I traced the fault to an excessive increment of `pos` inside [`ResumeBlockComment`]. A simple length comparison before incrementing seems to clear it up [1].

I don't suspect a regression as #34 only touched `ResumeLineComment`, and a trailing line comment doesn't raise any exception:

![unpatched-trailing-line-comm](https://user-images.githubusercontent.com/59004801/137476898-cbfa2593-7943-4d95-b3d2-f78feeb2f256.png)

- [LexRust-dont-style-past-doc-length.zip](https://github.com/ScintillaOrg/lexilla/files/7352941/LexRust-dont-style-past-doc-length.zip)
- [LexRust-test-files.zip](https://github.com/ScintillaOrg/lexilla/files/7352944/LexRust-test-files.zip)

---
[1] The best way to reproduce would be unzipping the test files first, then compiling `TestLexers` with MSVC in debug mode: CXX_FLAGS=-Zi -TP -MP -W4 -Od -MTd -DDEBUG -EHsc -std:c++17

Expect something like:

```
Lexing rust\Issue35.rs
Assertion failed: (startPosStyling + validLen) < Length(), file C:\Users\Rob\source\git\scintilla-contrib\lexilla-dev\lexilla\lexlib\LexAccessor.h, line 178
```

[this debug assertion]: https://github.com/ScintillaOrg/lexilla/blob/782725aeed8db061e41fe14971887188380481b3/lexlib/LexAccessor.h#L173-L181

[`ResumeBlockComment`]:
https://github.com/ScintillaOrg/lexilla/blob/4269001e24d21cf232c2150bef1f47c8b5fbf530/lexers/LexRust.cxx#L527-L536

**Comment by nyamatongwe** [comment]
Going past the end is quite common in lexers as it can avoid complicating the logic. The calls made by lexers are hardened to deal with this so its not a big problem if it occurs. The assertion only appears in debug builds. Its nice to avoid out-of-bounds where it doesn't require too much work but it doesn't seem worth the effort to try to eliminate it completely.

**Comment by dail8859** [comment]
Hi @nyamatongwe 

This assertion error shows up quite often running my application in debug mode. It shows up anytime there is a new blank document (length == 0, language == "null") opened. Is there something I can do as a developer using Lexilla to handle this more gracefully? Or is there something that can be done with the null lexer? Thanks.

**Comment by elcuco** [comment]
> Going past the end is quite common in lexers as it can avoid complicating the logic. The calls made by lexers are hardened to deal with this so its not a big problem if it occurs. The assertion only appears in debug builds. Its nice to avoid out-of-bounds where it doesn't require too much work but it doesn't seem worth the effort to try to eliminate it completely.

That is hardly usable. I can reproduce this by opening an empty file.  Yes, you can `-DNDEBUG` to convince libc to disable this check. Under linux - I think - this affects only this function. I am unsure about OSX, or Win32.

**Comment by nyamatongwe** [comment]
@dail8859 Its likely the null lexer could be changed fairly easily to not style past the end of an empty document. I'm travelling on vacation so can't easily check the code now.

**Comment by nyamatongwe** [comment]
@elcuco Are you referring to Rust here? I don't think it should do anything for an empty file. Can you please post a stack trace?

**Comment by dail8859** [comment]
@nyamatongwe 

It looks like I solved the root cause of the issue from my side. After setting the lexer I was calling `Colourise(0, 1)` for some reason. I removed the call and the assertion error goes away with no noticable reason to keep it.

Side question...when is it required to call `Colourise()` on a document?

**Comment by nyamatongwe** [comment]
> @dail8859 when is it required to call Colourise() on a document?

When the application wants styling data to be accurate beyond the visible text. Perhaps you want to search for a string but just in comments or would like to fold each `function` structure.

**Comment by dail8859** [comment]
@nyamatongwe Makes perfect sense. Thanks!
