### ISSUE TITLE
F#: Allow strings to end with escaped '\'s

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#38]
`LexFSharp` is confused by strings with one or more escaped backslashes in terminal position. Sequences like `"\\"` and `"\\\\"` are lexed as if the closing quote were escaped:

![Screenshot 2021-10-30 222709](https://user-images.githubusercontent.com/59004801/140433115-d9ea653f-55e9-443d-984f-37c8a55e129b.png)

By contrast, a single escaped backslash character keeps to its proper bounds:

![Screenshot_2021-11-03_22-44-35](https://user-images.githubusercontent.com/59004801/140433164-989c6920-e862-4029-aab3-4ecdcbdcefc3.png)

This is a trivial fix: [LexFSharp-Allow-Backslashes-at-Str-Ends.zip](https://github.com/ScintillaOrg/lexilla/files/7479440/LexFSharp-Allow-Backslashes-at-Str-Ends.zip)

**Comment by nyamatongwe** [comment]
That is a good improvement, handling all likely cases well. There could be cases with 3 backslashes but that should be rare.

Since there is a release soon, committing will wait until after the release.

**Comment by rdipardo** [comment]
Waiting on this one was the right idea; it turned out to be a less trivial problem than I assumed.

With the first patch, strings don't terminate if you escape a backslah and a double-quote together, a conceivabe use case when interpolating path names that need quoting:

![Screenshot 2021-11-06 104537](https://user-images.githubusercontent.com/59004801/140613736-d7d1bfed-ba02-442b-a294-6375414ccc3c.png)

Simply checking for an adjacent double-quote leads to a new regression: an internal series of backslashes turns any escaped double-quote into a string delimiter:

![LexFSharp-pre-patched-esc-quotes](https://user-images.githubusercontent.com/59004801/140612919-887432ed-1ac4-4c9d-8ba9-7edd6891e47e.gif)

In this new patchset I settled on a helper function to distinguish terminating quotes from escaped ones; the tests were amended to anticiapte more edge cases: [LexFSharp-Fix-Issue38-Rev-2.zip](https://github.com/ScintillaOrg/lexilla/files/7490613/LexFSharp-Fix-Issue38-Rev-2.zip)

**Comment by rdipardo** [comment]
The most recent patch for `test/examples/fsharp/x.fs` has "escapeWinPath" around line 48, but the function thus named is actually unescaping its argument.

Here's a slightly corrected patch, otherwise identical to the previous: [0005-Test-LexFSharp-Prefer-unescape-in-func-name.diff.txt](https://github.com/ScintillaOrg/lexilla/files/7498340/0005-Test-LexFSharp-Prefer-unescape-in-func-name.diff.txt)

**Comment by nyamatongwe** [comment]
Committed as fc598896a66f5c507230bc07a31042bb7a8cef25.

**Comment by nyamatongwe** [comment]
Included in Lexilla 5.1.4.
