### ISSUE TITLE
Batch syntax highlighting doesn't work properly with expansion modifiers

### ISSUE THREAD

**Issue by riQQ** [ScintillaOrg/lexilla#4]
Example: `echo %~dp09`
Only `%~dp0` should be highlighted as a batch identifier instead of `%~dp09`.

Notepad++ Screenshot (the screenshot was made with an older version, but it's still reproducable with Notepad++ 7.9.5)
![Bash syntax highlighting](https://cloud.githubusercontent.com/assets/3404787/7617791/e01caa48-f9ad-11e4-8097-fc51693ea7fb.png)

This was already reported at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/63.

**Comment by nyamatongwe** [comment]
It would help to include a link to documentation of the expansion modifier syntax.

**Comment by ArkadiuszMichalski** [comment]
>Only %~dp0 should be highlighted as a batch identifier instead of %~dp09.

I see different editors do it differently:
- VSC `~dp0`
- Sublime Text `%~dp0`
- all based on Scintilla `%~dp09`

Regardless, `9` should not be taken into account, because it's just string, like `echo %~dp0hello` or `echo %~dp0 hello`. 

It may be useful:
https://ss64.com/nt/syntax-args.html

Running `for /?` in cmd will return some information:

```
In addition, substitution of FOR variable references has been enhanced.
You can now use the following optional syntax:

%~I         - expands %I removing any surrounding quotes (")
%~fI        - expands %I to a fully qualified path name
%~dI        - expands %I to a drive letter only
%~pI        - expands %I to a path only
%~nI        - expands %I to a file name only
%~xI        - expands %I to a file extension only
%~sI        - expanded path contains short names only
%~aI        - expands %I to file attributes of file
%~tI        - expands %I to date/time of file
%~zI        - expands %I to size of file
%~$PATH:I   - searches the directories listed in the PATH
               environment variable and expands %I to the
               fully qualified name of the first one found.
               If the environment variable name is not
               defined or the file is not found by the
               search, then this modifier expands to the
               empty string

The modifiers can be combined to get compound results:

%~dpI       - expands %I to a drive letter and path only
%~nxI       - expands %I to a file name and extension only
%~fsI       - expands %I to a full path name with short names only
%~dp$PATH:I - searches the directories listed in the PATH
               environment variable for %I and expands to the
               drive letter and path of the first one found.
%~ftzaI     - expands %I to a DIR like output line

In the above examples %I and PATH can be replaced by other valid
values.  The %~ syntax is terminated by a valid FOR variable name.
Picking upper case variable names like %I makes it more readable and
avoids confusion with the modifiers, which are not case sensitive.
```

**Comment by nyamatongwe** [comment]
The code that implements this is around line 404 of LexBatch.cxx. Changing it is complicated by the need to update several variables to retreat back past additional characters to the digit.

**Comment by nyamatongwe** [comment]
Pull request committed with minor changes.

Credited to "riQQ". If you want a different name in the credits then tell me.

**Comment by riQQ** [comment]
That's fine, thanks.

**Comment by lifenjoiner** [comment]
Came here for 1 more special case:
```bat
for /F "tokens=1,3,4 delims=:" %%a in ("!inioff!") do (
set "inioff=%%~a"
set "base=%%~b"
set /A "size=%%~c" )
```
![ppt](https://user-images.githubusercontent.com/19585474/118584084-c3211700-b7c8-11eb-80d2-2dffd943c897.png)
`"` is also colorized. The `%%~` type variable ending recognition needs to be improved if there is `"` (and other special characters).
It can be observed in (tested):
https://github.com/ScintillaOrg/lexilla/blob/e9bf2252938311d2c75119a59cf776885c5e224e/lexers/LexBatch.cxx#L400-L450
Initial discussion at https://github.com/zufuliu/notepad2/issues/332#issuecomment-842744692 as the item 1.

**Comment by lifenjoiner** [comment]
Patch:
[Improve-ending-recognition-of-batch-variable-expansion.zip](https://github.com/ScintillaOrg/lexilla/files/6498975/Improve-ending-recognition-of-batch-variable-expansion.zip)

**Comment by nyamatongwe** [comment]
Committed b39c460 patch with some changes to x.bat.styled and x.bat.folded. The patch was a little strange as it appeared to be making new x.bat.styled.new and x.bat.folded.new files but with just the new text as if they were based on a shortened version of x.bat with just the new examples.

Its perfectly OK to provide a new example file (and its processed forms) just for a bug. For example, test/examples/markdown/Bug2235.md.

When adding to an existing example, run the tester, check the resulting .new files then rename them without the .new (replacing the old .styled/.folded) then include these modifications in the patch.

**Comment by lifenjoiner** [comment]
OK, got it. I misunderstood the test part, thought the owner will do the final step 😅, as drawn by the popup `https://github.com/ScintillaOrg/lexilla/blob/e9bf2252938311d2c75119a59cf776885c5e224e/CONTRIBUTING#L6-L10`:
https://github.com/ScintillaOrg/lexilla/blob/e9bf2252938311d2c75119a59cf776885c5e224e/CONTRIBUTING#L6-L10
Thanks for your effort!

As we use git/hg, changes can be easily traced, may just patching the .styled/.folded files be OK?

**Comment by nyamatongwe** [comment]
There's more explanation further on in CONTRIBUTING. Sending patches containing just the additions is good.
