### ISSUE TITLE
Add New Syntax

### ISSUE THREAD

**Issue by Erghel** [ScintillaOrg/lexilla#42]
Dear developers. Please add LOLCODE, Brainfuck, YoptaScript, Pawn, Beef, Crystal and Eiffel syntax. It will be amazing - make brainfuck (or smth else) code in Notepad++

**Comment by nyamatongwe** [comment]
Eiffel is supported by the "eiffel" lexer.

Lexers are added when someone decides to contribute an implementation.

**Comment by Erghel** [comment]
Oh, okay!
