### ISSUE TITLE
Language Support: Dart

### ISSUE THREAD

**Issue by A-bahattab** [ScintillaOrg/lexilla#58]
We would like Dart language to be supported. Thank you.

**Comment by TuupleMasterAndroid** [comment]
Need support for Dart File

**Comment by zufuliu** [comment]
There is a lexer that can be ported to Lexilla:
https://github.com/zufuliu/notepad2/blob/main/scintilla/lexers/LexDart.cxx

**Comment by Tokenizer94** [comment]
Any update?

**Comment by rajabiy** [comment]
+

**Comment by A-bahattab** [comment]
Waiting...

**Comment by insinfo** [comment]
Is dart supported now?
