### ISSUE TITLE
Code folding for Ruby 3 endless method definition

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#65]
https://rubyreferences.github.io/rubychanges/3.0.html#endless-method-definition
https://docs.ruby-lang.org/en/master/doc/syntax/methods_rdoc.html

Test case and patch 
[ruby-shorthand-method.zip](https://github.com/ScintillaOrg/lexilla/files/8262926/ruby-shorthand-method.zip)

```ruby
def dbg_args(a, b=1, c:, d: 6, &block) = puts("Args passed: #{[a, b, c, d, block.call]}")
dbg_args(0, c: 5) { 7 }

class A

	def a=(value)
		return 1 + value
	end

	def ==(other) = true
end
```

**Comment by zufuliu** [comment]
Please suspend the patch, I'm still work on this.

**Comment by zufuliu** [comment]
[ruby-method.zip](https://github.com/ScintillaOrg/lexilla/files/8275780/ruby-method.zip)

Finished the patch, it's now contains two changes:
1. operator method highlighting fixes inside `ColouriseRbDoc()`.
2. endless method code folding fixes inside `FoldRbDoc()`.

attachment contains LexRuby.cxx and test case (a nonsense but valid and runnable Ruby file):
```ruby
def dbg_args(a, b=1, c:, d: 6, &block) = puts("Args passed: #{[a, b, c, d, block.call]}")
dbg_args(0, c: 5) { 7 }

class A
	def attr = @attr
	def attr=(value)
		@attr = value
	end
	def attr? = !!@attr
	def attr! = @attr = true
	# unary operator
	def -@ = 1
	def +@ = 1
	def ! = 1
	def !@ = 1
	# binary operator
	def +(value) = 1 + value
	def -(value) = 1 - value
	def *(value) = 1 * value
	def **(value) = 1 ** value
	def /(value) = 1 / value
	def %(value) = 1 % value
	def &(value) = 1 & value
	def ^(value) = 1 ^ value
	def >>(value) = 1 >> value
	def <<(value) = 1 << value
	def ==(other) = true
	def !=(other) = true
	def ===(other) = true
	def =~(other) = true
	def <=>(other) = true
	def <(other) = true
	def <=(other) = true
	def >(other) = true
	def >=(other) = true
	# element reference and assignment
	def [](a, b) = puts(a + b)
	def []=(a, b, c)
		puts a + b + c
	end
	# test short method name
	def a = 1
	def ab = 1
end
```

**Comment by nyamatongwe** [comment]
The change appears to fold the current example x.rb incorrectly.

![Issue65Fold](https://user-images.githubusercontent.com/225818/158720997-2d2659d8-9636-4999-a880-afc92604001e.png)

**Comment by zufuliu** [comment]
> The change appears to fold the current example x.rb incorrectly.

Is due to reset `method_definition` inside `atEOL` block is lost,  updated patch with more tests.
[ruby-method-0317.zip](https://github.com/ScintillaOrg/lexilla/files/8285463/ruby-method-0317.zip)

It appears further fix is needed for better highlighting class method and singleton method. see https://docs.ruby-lang.org/en/master/doc/syntax/methods_rdoc.html#label-Scope
```ruby
class C
  def self.my_method
    # ...
  end
end

greeting = "Hello"

def greeting.broaden
  self + ", world!"
end

def String.hello
  "Hello, world!"
end
```

**Comment by zufuliu** [comment]
[ruby-method0318.zip](https://github.com/ScintillaOrg/lexilla/files/8304883/ruby-method0318.zip)

I think the change is completed, with following changes:
1. operator method and class method highlighting, which contains `ClassifyWordRb()` and `afterDef` related changes.
2. heredoc improvement, the changes inside `sureThisIsNotHeredoc()` and `if (HereDoc.State == 1 && IsEOLChar(ch))`  block.
3. fix code folding for endless method definition.
4. add code folding for string array `SCE_RB_STRING_QW`.
5. removed `buffer_ends_with_eol` block, instead changed last block into `if (atEOL || (i == endPos - 1))`. this fixes code folding for last `end` in x.rb.

new test cases for heredoc:
```ruby
# heredoc prevStyle == SCE_RB_GLOBAL
$stdout.puts <<~EOT.chomp
	squiggly heredoc
EOT
# heredoc method call, other argument
A::say <<-ONE, __FILE__, __LINE__
content for heredoc one
ONE
```

**Comment by zufuliu** [comment]
Fix a typo:
```diff
- afterDef = word_style = SCE_RB_DEFNAME;
+ afterDef = word_style == SCE_RB_DEFNAME;
```

[ruby-method0318-2.zip](https://github.com/ScintillaOrg/lexilla/files/8305018/ruby-method0318-2.zip)

**Comment by nyamatongwe** [comment]
Committed d666960259ab726899ad0dc47e05285ce0d95626, 9c8da5a671e284aff3068fbfbbe16ae3a63e0b5e, and 6d548550bee60e5f01b069a9f5afb686914fb13d from ruby-method-0317.zip. From ruby-method0318-2.zip (5) as a6ec4d07bb8f3654f0b917919b9be3fbef6ffe0e and (4) as ee1b3fa38c23bdf4af3cd77075f1d7bc3b598246.

For (1), (2), and (3) the scope of each change is unclear and there is no example for (1).

**Comment by zufuliu** [comment]
Attachment is (2) heredoc changes.
[ruby-heredoc-0325.zip](https://github.com/ScintillaOrg/lexilla/files/8350717/ruby-heredoc-0325.zip)

**Comment by zufuliu** [comment]
Attachment is class method highlighting changes (on top of heredoc changes).
[ruby-class-method-0325.zip](https://github.com/ScintillaOrg/lexilla/files/8350855/ruby-class-method-0325.zip)

Differences for with (right) and without (left) the change:

![ruby-class-method](https://user-images.githubusercontent.com/2289926/160128997-5921ebb0-d2c0-472f-afdd-0a59726b2c31.png)
