### ISSUE TITLE
Ruby indented heredoc styles final newline character as delimiter, not heredoc

### ISSUE THREAD

**Issue by nyamatongwe** [ScintillaOrg/lexilla#66]
In this example, the first item is a standard heredoc and the second is an indented heredoc because of the `-` although it is not actually indented.

~~~ruby
<<T
X
T

<<-T
X
T
~~~

The content line is `X\n` or `X\r\n`. Ruby defines that a heredoc `includes the ending newline`.
https://ruby-doc.org/core-2.3.1/doc/syntax/literals_rdoc.html#label-Here+Documents

The lexer correctly styles the `\n` for the standard heredoc as `SCE_RB_HERE_Q` but as `SCE_RB_HERE_DELIM` for the indented heredoc. This causes incorrect visuals when line ends are visible or an `eolfilled` style is specified. It also causes `\r` and `\n` to be styled differently causing problems with the automated tests.

This can be fixed with
~~~patch
diff --git a/lexers/LexRuby.cxx b/lexers/LexRuby.cxx
index b1bebb34..0fc04707 100644
--- a/lexers/LexRuby.cxx
+++ b/lexers/LexRuby.cxx
@@ -1321,7 +1321,7 @@ static void ColouriseRbDoc(Sci_PositionU startPos, Sci_Position length, int init
                                                 i - HereDoc.DelimiterLength + 1,
                                                 lengthDoc,
                                                 HereDoc.Delimiter)) {
-                styler.ColourTo(i - 1 - HereDoc.DelimiterLength, state);
+                styler.ColourTo(i - HereDoc.DelimiterLength, state);
                 styler.ColourTo(i, SCE_RB_HERE_DELIM);
                 state = SCE_RB_DEFAULT;
                 preferRE = false;
~~~

**Comment by zufuliu** [comment]
Good catch.

**Comment by nyamatongwe** [comment]
Committed fix.
