### ISSUE TITLE
Ruby unrecognized heredoc

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#67]
Following heredoc are not unrecognized, first one due to `prevStyle == SCE_RB_GLOBAL` and method call `.chomp` after delimiter, second one due to more arguments (`,`) after delimiter:

```ruby
# heredoc prevStyle == SCE_RB_GLOBAL
$stdout.puts <<~EOT.chomp
	squiggly heredoc
EOT
# heredoc method call, other argument
A::say <<-ONE, __FILE__, __LINE__
content for heredoc one
ONE
```

Attachment fix.
[ruby-heredoc-0325.zip](https://github.com/ScintillaOrg/lexilla/files/8350717/ruby-heredoc-0325.zip)

_Originally posted by @zufuliu in https://github.com/ScintillaOrg/lexilla/issues/65#issuecomment-1079007534_

**Comment by nyamatongwe** [comment]
Committed fixes.
