### ISSUE TITLE
Ruby improve class method highlighting

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#68]
Attachment is class method highlighting changes (on top of heredoc changes).
[ruby-class-method-0325.zip](https://github.com/ScintillaOrg/lexilla/files/8350855/ruby-class-method-0325.zip)

Differences for with (right) and without (left) the change:

![ruby-class-method](https://user-images.githubusercontent.com/2289926/160128997-5921ebb0-d2c0-472f-afdd-0a59726b2c31.png)

_Originally posted by @zufuliu in https://github.com/ScintillaOrg/lexilla/issues/65#issuecomment-1079026497_

**Comment by nyamatongwe** [comment]
Committed fix.
