### ISSUE TITLE
Need break loop if loaded while `Lexilla::Load`ing from pathes

### ISSUE THREAD

**Issue by lifenjoiner** [ScintillaOrg/lexilla#7]
Add `break;` between:
https://github.com/ScintillaOrg/lexilla/blob/e9bf2252938311d2c75119a59cf776885c5e224e/access/LexillaAccess.cxx#L194-L195

**Comment by nyamatongwe** [comment]
I don't understand. Are you wanting to stop the loading of multiple libraries?

**Comment by lifenjoiner** [comment]
Yes. I thought 1 of the same name dynamic libraries is loaded usually (the 1st).
Are you making it access `multiple libraries` intentionally? If so, this is a false report, it adopts the last one.

**Comment by nyamatongwe** [comment]
I hadn't thought of it as choosing one from multiple same name libraries. To me this is: load multiple libraries where there may (or may not) be overlaps in which lexers are available. When requesting a lexer choose a library from the list that provides it, preferring libraries earlier in the list.
