### ISSUE TITLE
External lexer library loading problem (from Scintilla4 to Scintilla5)

### ISSUE THREAD

**Issue by donho** [ScintillaOrg/lexilla#71]
`SCI_LOADLEXERLIBRARY` message is removed from the Scintilla 5. 
Is there any function call or message replacement in Lexilla5/Scintilla5, 
or the application should implement the loading external lexer library part?

**Comment by nyamatongwe** [comment]
Don HO:

> SCI_LOADLEXERLIBRARY message is removed from the Scintilla 5.
> Is there any function call or message replacement in Lexilla/Scintilla,
> Or it's the application which should implement the loading part?

   The Lexilla distribution includes an ‘LexillaAccess’ module in the ‘access’ directory to provide a basic loader. This is separate from the code included in the Lexilla shared library as it is used to load the shared library. Applications with more advanced requirements may need to implement their own loader or customize ‘LexillaAccess’.
https://www.scintilla.org/LexillaDoc.html

   Neil

**Comment by nyamatongwe** [comment]
Is the problem that LexillaAccess wasn't being used?

Is the problem that the external lexers implement GetLexerFactory but not CreateLexer and LexillaAccess wants CreateLexer? You could add support for GetLexerFactory into LexillaAccess. Or add CreateLexer to the external lexers.

**Comment by donho** [comment]
Thank you Neil for your reply.
It was much less fastidious than I thought: 
In the case of Notepad++, only the fnCreateLexer function call from lexer (instead of CreateLexer of Lexilla) is needed.
I've modified both [Notepad++ (with Scintilla5)](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11468) and [Papyrus Plugin](https://github.com/blu3mania/npp-papyrus/pull/24) than it works like before.
Thank you again for your support.
Don
