### ISSUE TITLE
Unify `_WIN32` testing conditionals

### ISSUE THREAD

**Issue by lifenjoiner** [ScintillaOrg/lexilla#9]
Although they do work, `#if _WIN32` and `#if !_WIN32` would be better to be updated to `#ifdef _WIN32` and `#ifndef _WIN32`, which are the more common forms. And there are `defined(_WIN32)`s, keeping the same style would be better.

**Comment by nyamatongwe** [comment]
I do not see the point here. The current form works and is consistent throughout Lexilla.

**Comment by lifenjoiner** [comment]
First of all, it's not a bug.

Why I mention it is because of when I read the header files that shipped with compilers, I always see the forms of:
1. `#if number`, 1 or 0
2. `#ifdef MacroName`, `#ifndef MacroName`
3. `if defined(MacroName)`, `if !defined(MacroName)`

I haven't seen `#if MacroName` or `#if !MacroName` before. I don't know why it's rarely used.

**Comment by nyamatongwe** [comment]
A problem with `#ifdef` is that there can only be a single term. If the expression could possibly become more complex, then `#if`, possibly with `defined()` is a more stable choice. This is often the case with platform definitions. Today's `#ifdef _WIN32` may become `#if defined(_WIN32) || defined(__APPLE__)`. The only place I'd use `#ifdef` now is in header inclusion protectors as they should never change.
