### ISSUE TITLE
Julia

### ISSUE THREAD

**Issue by czylabsonasa** [ScintillaOrg/lexilla#97]
`#` character constant after a `!=` operator confuses the parser: [see](https://github.com/geany/geany/pull/2584#issuecomment-1201574588)

**Comment by nyamatongwe** [comment]
That is interpreting the `'` as [adjoint ](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Base.adjoint).
> a trailing apostrophe is the [adjoint](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Base.adjoint) (that is, the complex transpose) operator Aᴴ

The lexer maintains a `transpose` state to differentiate this use from `Char` literals.

**Comment by nyamatongwe** [comment]
Pull request #98 committed.

**Comment by nyamatongwe** [comment]
Included in 5.1.9.
